### PR TITLE
Check value is in range before casting from double to uint32_t

### LINKED ISSUE #1827: undefined behavior in cast from double to long
There is a UBSAN failure in [this cast](https://github.com/Exiv2/exiv2/blob/b364b1db572703fd88299db9fc9f6f8d1064520f/src/tags_int.cpp#L2590) from `double` to `long`:

```c
ur.second = static_cast<long>(tmp + 0.5);
```

To reproduce, you need a UBSAN build with clang:

```
mkdir build-asan
cd build-asan
cmake -DCMAKE_BUILD_TYPE=Debug -DEXIV2_TEAM_USE_SANITIZERS=ON -DCMAKE_CXX_COMPILER=$(which clang++) ..
make -j $(nproc)
./bin/exiv2 poc.crw
```

poc: [poc.tar.gz](https://github.com/Exiv2/exiv2/files/6917851/poc.tar.gz)

output:

```
/home/kev/work/exiv2/src/tags_int.cpp:2590:43: runtime error: 3.95874e+164 is outside the range of representable values of type 'long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/kev/work/exiv2/src/tags_int.cpp:2590:43 in 
```

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes: #1827

The `static_cast<long>` can cause a UBSAN failure if the value of `tmp` is out of range. It was also incorrect to cast to `long`, because the type of `ur.second` is `uint32_t`.

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
I wonder if we should use [nearbyint](https://en.cppreference.com/w/cpp/numeric/math/nearbyint) for the rounding on the main branch. (Can't use it on 0.27-maintenance because it's a C++11 feature.) C++11 also has an `lround` function, but it doesn't seem to be any better at handling out-of-range values, and it's return type is `long` which isn't platform independent.

File: src/tags_int.cpp [hunk 1]
```diff
@@ -2585,12 +2585,22 @@ namespace Exiv2 {
...
     {
         URational ur(1, 1);
-        double tmp = std::exp(std::log(2.0) * static_cast<double>(shutterSpeedValue));
+        const double tmp = std::exp(std::log(2.0) * static_cast<double>(shutterSpeedValue));
         if (tmp > 1) {
-            ur.second = static_cast<long>(tmp + 0.5);
+            // Add 0.5 for rounding.
+            const double x = tmp + 0.5;
+            // Check that x is within the range of a uint32_t before casting.
+            if (0 <= x && x <= std::numeric_limits<uint32_t>::max()) {
```
Comment (hassec) [inline src/tags_int.cpp:2593]:
```suggestion
            if (x <= std::numeric_limits<uint32_t>::max()) {
```
This is to fix the LGTM warning because `x>=0` is always true in the `tmp > 1` branch

**Comment by hassec** [comment]
:+1: for using C++11 features in `main`. 

Any reason to use `nearbyint` over just `std::round`? `std::round` would give use the rounding behavior we have implemented right now, while `nearbyint` would depend on the rounding mode that is set

**Comment by kevinbackhouse** [comment]
@hassec: you're right, `std::round` is better than `std::nearbyint`. I overlooked it when I was reading about `std::lround`!

**Review by hassec — APPROVED** [review]
