### PR TITLE
Extract XMP data from embedded JPEG preview inside RAF files

### LINKED ISSUE #2610: Missing Exif.Fujifilm.Rating tag for Fujifilm XT-5 RAF files
#### **Describe the bug**
The sample file  **_DSF0052.RAF** has a 4-star rating added via camera X-T5. When importing into darktable, the image as no rating. I've tracked down this to libexiv2. exiv2 reports no **Exif.Fujifilm.Rating** for any of my XT-5 files, for example by using `exiv2 -pt _DSF0052.RAF`.
I validated via exiftool that the rating is indeed encoded:

````
exiftool -Rating _DSF0052.RAF
Rating                          : 4
````

#### **To Reproduce**
 1. Download the https://chaospixel.com/pub/temp/_DSF0052.RAF file (CC0 licensed, shoot by me, feel free to use it in any way).
 2. Run `exiv2 -pt _DSF0052.RAF`
 3. Search or grep for **Exif.Fujifilm.Rating**, it's not available.

#### **Expected behavior**
The output of exiv2 should print **Exif.Fujifilm.Rating** and the rating should be applied during import into darktable.

#### **Desktop (please complete the following information):**
- OS and version: Linux Debian Bullseye with exiv2 built from source (0.27.6)
- Exiv2 version and source: 0.27.6 (tried 0.28.0 as well)
- Compiler and version: gcc version 10.2.1 20210110 (Debian 10.2.1-6)
- Compilation mode and/or compiler flags: -O3 -DNDEBUG

### PR DESCRIPTION
**Pull request by cytrinox**
The Fujifilm X-T5 camera stores in-camera rating for RAF images by using XMP. But the XMP data is not directly encoded into the RAF structure - instead it is attached as a second APP1 segment to the embedded JPEG preview file.

This patch extracts the JPEG preview and parses it like a standalone JPEG file.

fixes #2610

### CODE REVIEW

**Comment by cytrinox** [comment]
To verify https://github.com/Exiv2/exiv2/issues/2610 one can use:

    exiv2 --Print IkytEX ../_DSF0052.RAF

The XMP rating is now printed:

    Xmp.xmp.Rating                               XmpText    4

**Comment by cytrinox** [comment]
@kmilos Here we go. Maybe you can have a look at it - I've touched C++ code long time ago :smile: 

There is one thing that could be improved: The JpegImage metadata parser already parses exif and other information. There is no need to keep the old *direct* method by using TiffParser. But I don't know how the get the byte order for `setByteOrder(bo);`.

File: src/rafimage.cpp [hunk 1]
```diff
@@ -248,17 +249,31 @@ void RafImage::readMetadata() {
...
-  ByteOrder bo = TiffParser::decode(exifData_, iptcData_, xmpData_, buf.c_data(), buf.size());
+  // Extracting metadata from first APP1 container
+  constexpr byte tiff_offset = 12;
+  ByteOrder bo = TiffParser::decode(exifData_, iptcData_, xmpData_, jpg_buf.c_data() + tiff_offset, jpg_buf.size() - tiff_offset);
+
+  // If there is no XMP data in first APP1 EXIF structure, there is maybe
+  // another APP1 container for XMP. Just use the JpegImage metadata parser for that.
+  if(xmpData_.empty()) {
+    BasicIo::UniquePtr jpg_io = std::make_unique<Exiv2::MemIo>(jpg_buf.data(), jpg_buf.size());
+    auto jpg_img = JpegImage(std::move(jpg_io), false);
```
Comment (kmilos) [inline src/rafimage.cpp:270]: Why not use this single decoder to extract both Exif and XMP in one shot?

I guess it might not be guaranteed that the above Exif APP1 segment assumed to be handled by TiffParser comes first...

Comment (cytrinox) [reply src/rafimage.cpp:270]: @kmilos Yes, thats my guess, too. And I don't know how I should get the byte order for `setByteOrder(bo);`.

Comment (kmilos) [reply src/rafimage.cpp:270]: You don't need it or care about it here. The JpegImage figures it out internally anyway.

File: src/rafimage.cpp [hunk 2]
```diff
@@ -248,17 +249,31 @@ void RafImage::readMetadata() {
...
+    jpg_img.readMetadata();
+    const auto jpg_xmp_data = jpg_img.xmpData();
+    for(auto it = jpg_xmp_data.begin(); it != jpg_xmp_data.end(); ++it) {
```
[the remark this answers is not in the document]
Comment (neheb) [reply src/rafimage.cpp:273]: for range loop.

File: src/rafimage.cpp [hunk 3]
```diff
@@ -248,17 +249,31 @@ void RafImage::readMetadata() {
...
 
-  ByteOrder bo = TiffParser::decode(exifData_, iptcData_, xmpData_, buf.c_data(), buf.size());
+  // Extracting metadata from first APP1 container
+  constexpr byte tiff_offset = 12;
+  ByteOrder bo = TiffParser::decode(exifData_, iptcData_, xmpData_, jpg_buf.c_data() + tiff_offset, jpg_buf.size() - tiff_offset);
+
+  // If there is no XMP data in first APP1 EXIF structure, there is maybe
+  // another APP1 container for XMP. Just use the JpegImage metadata parser for that.
+  if(xmpData_.empty()) {
+    BasicIo::UniquePtr jpg_io = std::make_unique<Exiv2::MemIo>(jpg_buf.data(), jpg_buf.size());
```
Comment (neheb) [inline src/rafimage.cpp:269]: auto

File: src/rafimage.cpp (hunk 1 above)
Comment (kmilos) [reply src/rafimage.cpp:270]: I can maybe dig deeper into this, but not sure why `setByteOrder(bo)` is there to begin with... There is parsing of another Tiff structure in the RAF later, and that has it's own byte order (we don't know if it's guaranteed to be identical to the embedded JPEG one, but it most likely is given that it is serialized by the same firmware).

If you want to keep the same functionality, then you can just do something like `setByteOrder(jpg_img.byteOrder())` instead.

**Comment by kmilos** [comment]
Ah, probably want to wrap the whole JPEG parsing (incl. the two preview tags) in a try-catch now, or update the expected test output...

**Comment by cytrinox** [comment]
> Ah, probably want to wrap the whole JPEG parsing (incl. the two preview tags) in a try-catch now, or update the expected test output...

fixed.

File: src/rafimage.cpp [hunk 4]
```diff
@@ -248,23 +249,31 @@ void RafImage::readMetadata() {
...
+    jpg_img.readMetadata();
+    setByteOrder(jpg_img.byteOrder());
+    xmpData_ = jpg_img.xmpData();
+    exifData_ = jpg_img.exifData();
+    iptcData_ = jpg_img.iptcData();
+  } catch (const Exiv2::Error&) {
+  }
 
   exifData_["Exif.Image2.JPEGInterchangeFormat"] = getULong(jpg_img_offset, bigEndian);
   exifData_["Exif.Image2.JPEGInterchangeFormatLength"] = getULong(jpg_img_length, bigEndian);
```
Comment (kmilos) [inline src/rafimage.cpp:275]: These should be included in the `try {}` block above.

File: src/rafimage.cpp [hunk 5]
```diff
@@ -248,23 +249,31 @@ void RafImage::readMetadata() {
...
-  ByteOrder bo = TiffParser::decode(exifData_, iptcData_, xmpData_, buf.c_data(), buf.size());
+  // Retreive metadata from embedded JPEG preview image.
+  try {
+    auto jpg_io = std::make_unique<Exiv2::MemIo>(jpg_buf.data(), jpg_buf.size());
+    auto jpg_img = JpegImage(std::move(jpg_io), false);
+    jpg_img.readMetadata();
+    setByteOrder(jpg_img.byteOrder());
+    xmpData_ = jpg_img.xmpData();
+    exifData_ = jpg_img.exifData();
+    iptcData_ = jpg_img.iptcData();
```
Comment (kmilos) [inline src/rafimage.cpp:270]: Copy over `comment_` as well.

**Comment by kmilos** [comment]
Almost there! 👍

File: src/rafimage.cpp (hunk 5 above)
Comment (kmilos) [reply src/rafimage.cpp:270]: That's right, an added benefit.

Comment (cytrinox) [reply src/rafimage.cpp:270]: Done.

File: src/rafimage.cpp (hunk 4 above)
Comment (kmilos) [reply src/rafimage.cpp:276]: Hm, 50/50 on this one indeed...

Let's leave it as is then, and handle it separately if need be.

**Review by kmilos — APPROVED** [review]

**Comment by kmilos** [comment]
@Mergifyio backport 0.28.x
