### PR TITLE
Catch std::exception in iptcprint

### LINKED ISSUE #2050: std::overflow_error when fuzzing iptcprint
##### **Describe the bug**
running `./iptcprint iptcprint_poc` results in a crash:
```
inate called after throwing an instance of 'std::overflow_error'
  what():  Overflow in addition
Aborted
```

##### **To Reproduce**
- Platform: Ubuntu 20.04.4 LTS, x86_64
- Compiler: clang13
- POC: [iptcprint_poc.tar.gz](https://github.com/Exiv2/exiv2/files/7822748/iptcprint_poc.tar.gz)
- Reproduce: run `./iptcprint iptcprint_poc`

### PR DESCRIPTION
**Pull request by kevinbackhouse**
The `main` function in the `iptcprint` sample program catches `Exiv2::AnyError` but not `std::exception`. The poc attached to #2050 is a bogus image file that triggers a `std::overflow_error` in this call to `Safe::add()`:

https://github.com/Exiv2/exiv2/blob/0b17cc31f71a06766a38f6c19f71e806381fadea/src/rafimage.cpp#L308

In the exiv2 application, we catch those exceptions and print an error message. We just need to do the same in this sample application.

I also changed the error return code to `1`, because `-1` is non-standard.

### CODE REVIEW

File: samples/iptcprint.cpp [hunk 1]
```diff
@@ -68,5 +68,9 @@ try {
 }
 catch (Exiv2::AnyError& e) {
     std::cout << "Caught Exiv2 exception '" << e << "'\n";
-    return -1;
+    return 1;
```
Comment (piponazo) [inline samples/iptcprint.cpp:71]: Could we use here `EXIT_FAILURE`? I like to use those exit values macros for making the code more readable:

https://en.cppreference.com/w/cpp/utility/program/EXIT_status

It is also fine for me if you want to merge this directly, and we can do a whole replacement of exit values in another PR

**Review by piponazo — APPROVED** [review]
