### PR TITLE
[main] Fix integer overflow #2179

### LINKED ISSUE #2179: Integer overflow in Photoshop::setIptcIrb
Reported by OSS-Fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45302

There is an integer overflow here:

https://github.com/Exiv2/exiv2/blob/790fc465f486eb511b9bdbe2c0f53d7132256c9d/src/jpgimage.cpp#L185

The problem is that there is no check that `pos <= sizePsData`, so the subtraction can overflow. This problem used to be a latent bug, masked by the use of the signed type `long`, but the [recent](https://github.com/Exiv2/exiv2/pull/2118) switch to `size_t` has made it triggerable. This problem only exists on `main`. It does not affect any released versions of Exiv2.

poc: [poc.tar.gz](https://github.com/Exiv2/exiv2/files/8389029/poc.tar.gz)

To reproduce:

```bash
./bin/fuzz-read-print-write clusterfuzz-testcase-minimized-fuzz-read-print-write-4560990975426560
```

It doesn't actually cause a crash for me. OSS-Fuzz must be using different build settings to catch it. I had to set a breakpoint on `Exiv2::Photoshop::setIptcIrb` and step through the loop to see the overflow manually.

### PR DESCRIPTION
**Pull request by piponazo**
Fix #2179 

I considered adding a python test to process the POC file, but I realised that the `exiv2` application is not exercising the part of the code that has been modified. In #2179 @kevinbackhouse mentioned that in order to reproduce the issue, one needs to use the `fuzz-read-print-write` application. However that application only gets compiled in the FUZZ jobs.

Any ideas of how we could try to exercise that part of the code with a python test?

Other possibility would be to try to add a unit test which directly calls `Photoshop::setIptcIrb`. It might be a good opportunity for me to get more familiar with that part of the code base.

### CODE REVIEW

File: src/jpgimage.cpp [hunk 1]
```diff
@@ -179,21 +182,24 @@ DataBuf Photoshop::setIptcIrb(const byte* pPsData, size_t sizePsData, const Iptc
...
       psBlob.push_back(0x00);
   }
-  // Write existing stuff after record,
-  // skip the current and all remaining IPTC blocks
+
+  // Write existing stuff after record, skip the current and all remaining IPTC blocks
   size_t pos = sizeFront;
-  while (0 == Photoshop::locateIptcIrb(pPsData + pos, sizePsData - pos, &record, &sizeHdr, &sizeIptc)) {
+  long nextSizeData = Safe::add<long>(static_cast<long>(sizePsData), -static_cast<long>(pos));
+  enforce(nextSizeData >= 0, ErrorCode::kerCorruptedMetadata);
```
Comment (piponazo) [inline src/jpgimage.cpp:189]: The fix is in lines 188-189 & 196-197. I ended up using `Safe::add<long>` to make sure that there is not integer overflow and I also used later `enforce` to make sure that the substraction is positive.

File: unitTests/test_Photoshop.cpp [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+
+TEST(Photoshop_setIptcIrb, withEmptyDataReturnsEmptyBuffer) {
+  const IptcData iptc;
+  DataBuf buf = Photoshop::setIptcIrb(nullptr, 0, iptc);
+  ASSERT_TRUE(buf.empty());
+}
+
+TEST(Photoshop_setIptcIrb, detectIntegerOverflow_withDataFromPOC2179) {
+  const std::array<byte, 141> data{
+      0x38, 0x42, 0x49, 0x4d, 0x20, 0x20, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x38, 0x42, 0x49, 0x4d, 0x04, 0x04,
```
Comment (piponazo) [inline unitTests/test_Photoshop.cpp:142]: This is the test which is replicating the case detected by oss-fuzz. Note that the assertion is checking that an exception is thrown.

**Review by kmilos — DISMISSED** [review]
LGTM
