### PR TITLE
Avoid null pointer exception due to NULL return value from strchr

### LINKED ISSUE #793: null pointer dereference in http.cpp
There is a null pointer deference bug at [http.cpp:364](https://github.com/Exiv2/exiv2/blob/55dfdb9ab007d6e6d1d06240048690eaac23b305/src/http.cpp#L364). If the http server sends back a reply that does not contain a space character, then `strchr` will return `NULL`, leading to a null pointer dereference in `atoi`.

To reproduce the bug (tested on master: [55dfdb9](https://github.com/Exiv2/exiv2/commit/55dfdb9ab007d6e6d1d06240048690eaac23b305)) open two terminals. In the first terminal, start a fake webserver using [response1.txt](https://github.com/Exiv2/exiv2/files/3113957/response1.txt):

```
cat response1.txt | sudo nc -l -p 80
```

In the second terminal, try to connect to the fake webserver:

```
exiv2 http://127.0.0.1/test.jpg
```

There are several other calls to `strcat` and `strstr` in the same [block of code](https://github.com/Exiv2/exiv2/blob/55dfdb9ab007d6e6d1d06240048690eaac23b305/src/http.cpp#L339-L396). I have not written PoCs for them, but the calls to `strchr` on lines [351](https://github.com/Exiv2/exiv2/blob/55dfdb9ab007d6e6d1d06240048690eaac23b305/src/http.cpp#L351) and [362](https://github.com/Exiv2/exiv2/blob/55dfdb9ab007d6e6d1d06240048690eaac23b305/src/http.cpp#L362) also look vulnerable to me.

### PR DESCRIPTION
**Pull request by kevinbackhouse**
This fixes #793.

### CODE REVIEW

File: src/http.cpp [hunk 1]
```diff
@@ -329,10 +329,14 @@ int Exiv2::http(Exiv2::Dictionary& request,Exiv2::Dictionary& response,std::stri
...
-                    if ( strstr(buffer,blankLines[b]) ) {
+                    const char* blankLinePos = strstr(buffer,blankLines[b]);
+                    if ( blankLinePos ) {
                         bSearching = false ;
-                        body   = (int) ( strstr(buffer,blankLines[b]) - buffer ) + strlen(blankLines[b]) ;
-                        status = atoi(strchr(buffer,' ')) ;
+                        body   = blankLinePos - buffer + strlen(blankLines[b]);
+                        const char* firstSpace = strchr(buffer,' ');
+                        if (firstSpace) {
+                            status = atoi(firstSpace);
```
Comment (D4N) [inline src/http.cpp]: Assuming we never find a space, won't this mean that status will be kept as `200` (=OK)?

Comment (kevinbackhouse) [reply src/http.cpp]: I considered making more drastic changes to this code, but decided it would be better to just fix the security problems with minimal changes. If I was going to refactor this code, it looks to me like `status` and `result` could be merged into a single variable. The code that I added further down changes the value of `status` if no space is found.

**Review by D4N — COMMENTED** [review]
LGTM, please rebase your changes on `0.27-maintenance` and then I'll approve them.

**Comment by kevinbackhouse** [comment]
I rebased it onto `0.27-maintenance`.

**Review by D4N — APPROVED** [review]
Thanks for fixing this!
