### PR TITLE
Check if embedded RAF image is really a TIFF

### LINKED ISSUE #1791: 0.27.4 regression on (older) RAF files
See https://github.com/darktable-org/darktable/issues/9567

The S5Pro sample is from [RPU](https://raw.pixls.us/getfile.php/2634/nice/Fujifilm%20-%20FinePix%20S5Pro%20-%203:2.RAF).

Here's what I get under mingw64, but the same happens w/ the official MSVC build too:

```
$ exiv2 -Qd Fujifilm\ -\ FinePix\ S5Pro\ -\ 3_2.RAF
Exiv2 exception in print action for file Fujifilm - FinePix S5Pro - 3_2.RAF:
This does not look like a TIFF image
```

If I downgrade to exiv2 0.27.3:

```
$ exiv2 Fujifilm\ -\ FinePix\ S5Pro\ -\ 3_2.RAF
File name       : Fujifilm - FinePix S5Pro - 3_2.RAF
File size       : 25616736 Bytes
MIME type       : image/x-fuji-raf
Image size      : 1440 x 960
Camera make     : FUJIFILM
Camera model    : FinePix S5Pro
Image timestamp : 2018:06:15 12:57:09
Image number    :
Exposure time   : 1/13 s
Aperture        : F3.5
Exposure bias   : 0 EV
Flash           : No, compulsory
Flash bias      :
Focal length    : 18.0 mm (35 mm equivalent: 27.0 mm)
Subject distance:
ISO speed       : 100
Exposure mode   : Manual
Metering mode   : Multi-segment
Macro mode      :
Image quality   : NORMAL
Exif Resolution : 1440 x 960
White balance   : Auto
Thumbnail       : image/jpeg, 8438 Bytes
Copyright       :                                                                                                                                                                                                                               
Exif comment    :                                                                                                                                                                                                                               
```

### PR DESCRIPTION
**Pull request by kmilos**
Fixes #1791 

Essentially keeps the old, fallback (noop) behaviour after introduction of commit 45119e3

### CODE REVIEW

File: src/rafimage.cpp [hunk 1]
```diff
@@ -364,17 +364,25 @@ namespace Exiv2 {
         // sanity check.  Does tiff lie inside the file?
         enforce(Safe::add(tiffOffset, tiffLength) <= io_->size(), kerCorruptedMetadata);
 
-        DataBuf  tiff(tiffLength);
         if (io_->seek(tiffOffset, BasicIo::beg) != 0) throw Error(kerFailedToReadImageData);
-        io_->read(tiff.pData_, tiff.size_);
 
-        if (!io_->error() && !io_->eof())
+        // check if this really is a tiff (some older models just embed a raw bitstream)
+        io_->read(readBuff, 4);
```
Comment (hassec) [inline src/rafimage.cpp:370]: Looking at this read call, I've a question for @kevinbackhouse. Should all of our `read` calls become [`readOrThrow`](https://github.com/Exiv2/exiv2/pull/1790/files#diff-2831d8bda7242391cc6c1b0462a30ce372b3c56e083145b225cbc33dbbc4011fR99)?  

I guess if we really try to protect exiv2 even from malicious files, then it would be the safest approach, no?

File: src/rafimage.cpp [hunk 2]
```diff
@@ -364,17 +364,25 @@ namespace Exiv2 {
         // sanity check.  Does tiff lie inside the file?
         enforce(Safe::add(tiffOffset, tiffLength) <= io_->size(), kerCorruptedMetadata);
 
-        DataBuf  tiff(tiffLength);
         if (io_->seek(tiffOffset, BasicIo::beg) != 0) throw Error(kerFailedToReadImageData);
-        io_->read(tiff.pData_, tiff.size_);
 
-        if (!io_->error() && !io_->eof())
+        // check if this really is a tiff (some older models just embed a raw bitstream)
```
Comment (hassec) [inline src/rafimage.cpp:369]: Just wanted to make it a bit more clear that the behavior we want for the raw bitstream case is a "no-op"

```suggestion
        // Check if this really is a tiff and then call the tiff parser.
        // Check is needed because some older models just embed a raw bitstream.
        // For those files we skip the parsing step. 
```

**Review by hassec — CHANGES_REQUESTED** [review]
Thanks for preparing a fix! :+1:     
Would you mind adding a test case for this?

**Comment by kmilos** [comment]
> Would you mind adding a test case for this?

Do you have a suggestion on how to best do this? There wasn't a testcase for RAF files before (hence the regression), but at the same time these are large (20-60 MB) raw files I'd prefer not to commit to the repository...

File: src/rafimage.cpp (hunk 1 above)
Comment (kevinbackhouse) [reply src/rafimage.cpp:372]: @hassec: yes, I would like to migrate to `readOrThrow` wherever possible. I think incomplete reads are almost always caused by a corrupt input file. I think [this `read`](https://github.com/Exiv2/exiv2/blob/3575a8258e101c1294d9f8d229bae92dd600911f/src/jpgimage.cpp#L1293) is the only one that I have come across so far where an incomplete read isn't an error.

Comment (kevinbackhouse) [reply src/rafimage.cpp:372]: I think this is goof enough for now:

```suggestion
        if (io_->read(readBuff, 4) != 4) { throw Error(kerFailedToReadImageData); }
```

**Comment by hassec** [comment]
@kmilos thanks, that's actually a good point. 
I originally assumed we might test this with a `.exv` file, but that was wrong of me.   

I think let's for now open an issue where we keep track of things which require a "full" file for a test.   
And then we need to hopefully soon figure out a way to properly set up tests using normal files.

**Comment by kevinbackhouse** [comment]
@kmilos: You could try truncating the first few KB of a genuine RAF file and see it's enough to get code coverage on this new code. I have just been experimenting to see if the fuzzer is able to hit the new code, but it looks like it can't get past [this line](https://github.com/Exiv2/exiv2/blob/944e68fa153f21a75b257409d67d8b77910560bc/src/rafimage.cpp#L329). If necessary, I'm sure we would could handcraft a fake file to get coverage on this code.

**Comment by kevinbackhouse** [comment]
@kmilos: here's a file that gets coverage of the new code: [poc.tar.gz](https://github.com/Exiv2/exiv2/files/6874592/poc.tar.gz)

**Comment by kmilos** [comment]
@kevinbackhouse Thanks, but I don't get this poc sample, it's supposed to fail?

```
$ ./exiv2 poc.raf
Exiv2 exception in print action for file poc.raf:
This does not look like a TIFF image
```

We already have similar "baked" RAFs in test/data, but I don't think those are representative of what we want to test here?

Maybe I'll just try truncating real old and new RAF samples to some minimal size, should come under 1 MB...

**Comment by kevinbackhouse** [comment]
@kmilos: it's not a valid raf file. But it's very small and it gets code coverage, so it's better than nothing if we can't find a better example. This kind of small file is also useful for fuzzing because it helps the fuzzer to test more of the code branches.

**Comment by kevinbackhouse** [comment]
I tweaked one more byte and now it runs without error: [poc.tar.gz](https://github.com/Exiv2/exiv2/files/6877269/poc.tar.gz)

```
 ./bin/exiv2 poc.raf
File name       : poc.raf
File size       : 118 Bytes
MIME type       : image/x-fuji-raf
Image size      : 0 x 0
Thumbnail       : None
Camera make     : 
Camera model    : 
Image timestamp : 
File number     : 
Exposure time   : 
Aperture        : 
Exposure bias   : 
Flash           : 
Flash bias      : 
Focal length    : 
Subject distance: 
ISO speed       : 
Exposure mode   : 
Metering mode   : 
Macro mode      : 
Image quality   : 
White balance   : 
Copyright       : 
Exif comment    : 
```

**Review by hassec — DISMISSED** [review]
I like the suggestion of using the linked poc file :+1:

**Comment by kmilos** [comment]
Don't we want two test files? I.e. one more that does not contain the "II*" signature so we have coverage for both "new" and "old" code paths?

**Comment by hassec** [comment]
I just checked and we have 2 `*.raf` files, but they are both only to cover some error cases, that don't reach the part you touched here. 
So, @kmilos you are right, it would indeed be even better to cover both scenarios.

**Comment by kmilos** [comment]
I need to cook up these poc files a bit more, seems TIFF length of 0 will not throw that old error...

**Review by kevinbackhouse — APPROVED** [review]
