### PR TITLE
 Avoid negative integer overflow when chunkLength == 0

### LINKED ISSUE #789: SIGSEGV in PngImage::readMetadata()
There is a bug at [pngimage.cpp:469](https://github.com/Exiv2/exiv2/blob/55dfdb9ab007d6e6d1d06240048690eaac23b305/src/pngimage.cpp#L469). If `iccOffset == 0`, which happens if `chunkLength == 0`, then Exiv2 crashes with a SIGSEGV.

Here is the PoC, which I have tested on master ([55dfdb9](https://github.com/Exiv2/exiv2/commit/55dfdb9ab007d6e6d1d06240048690eaac23b305)): poc1. You can run the PoC like this:

```
$ exiv2 poc1.png
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes #789.

### CODE REVIEW

File: src/pngimage.cpp [hunk 1]
```diff
@@ -461,11 +461,12 @@ namespace Exiv2 {
...
                     // The ICC profile name can vary from 1-79 characters.
                     uint32_t iccOffset = 0;
-                    while (iccOffset < 80 && iccOffset < chunkLength) {
-                         if (chunkData.pData_[iccOffset++] ==  0x00) {
-                            break;
-                         }
-                    }
+                    do {
+                      if (iccOffset >= 80 || iccOffset >= chunkLength) {
+                        throw Exiv2::Error(kerFailedToReadImageData);
```
Comment (D4N) [inline src/pngimage.cpp]: Any particular reason why you have inserted this line? If I understand your patch correctly, then the actual fix is to replace the the while loop with a do-while loop and swap the conditions.

Comment (kevinbackhouse) [reply src/pngimage.cpp]: The bug happens when `chunkLength == 0`. The old loop would terminate immediately with `iccOffset == 0`. But the code after the loop assumes that `iccOffset > 0` because it is supposed to be the length of the string including the `'\0'` terminator. If you replaced this `throw` with a `break`, then the bug would still happen.

**Review by piponazo — DISMISSED** [review]

**Review by D4N — CHANGES_REQUESTED** [review]
Please squash these two commits into one: 1e0dec2 and 9192d62c170a858aeb09faa808d39fd825ebed42.

I'd really prefer a solution that does not incur another exception to be thrown. If you can find a way: that'd be great, but I'm fine with the PR if you prefer not to touch this further.

**Comment by kevinbackhouse** [comment]
@D4N: an alternative solution is disallow `chunkLength == 0` on [line 433](https://github.com/Exiv2/exiv2/pull/794/files#diff-3cdf312c2a771ea48fc0089e9d30d5e5R433). But I didn't do that because I wasn't sure if `chunkLength == 0` is invalid when `chunkType` is something different, like "IEND".

Why do you not want to throw an exception? Is it a performance thing?

**Review by piponazo — DISMISSED** [review]

**Comment by piponazo** [comment]
Thanks for the contribution! LGTM.

Would you mind to rebase the branch in top `0.27-maintenance` ?

File: src/pngimage.cpp (hunk 1 above)
Comment (D4N) [reply src/pngimage.cpp]: Unfortunately, I don't really know the details of the PNG format, so let's keep it this way.

**Review by D4N — DISMISSED** [review]
Thank you very much for your contribution!

**Comment by D4N** [comment]
@kevinbackhouse I've rebased the changes in your branch on top of `0.27-maintenance`.

**Review by D4N — DISMISSED** [review]

**Comment by D4N** [comment]
@piponazo @kevinbackhouse any objections to merging this?

**Review by piponazo — APPROVED** [review]
