### PR TITLE
fix(quicktimevideo) avoid out of bounds read, closes #2340

### LINKED ISSUE #2340: Out-of-bounds read in quicktimevideo.cpp
Reported by OSS-Fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50629

There's an out-of-bounds read here:

https://github.com/Exiv2/exiv2/blob/e4adf388aaaccccaf08fc0fc38419a5b0117b299/src/quicktimevideo.cpp#L671

The problem is that the buffer hasn't been nul-terminated.

quicktimevideo.cpp is a brand new file, so this definitely doesn't affect any released versions of exiv2.

poc: https://user-images.githubusercontent.com/4358136/186881088-a2b8c10c-c2b5-4f98-bc41-7736e86cbf1b.mp4

To reproduce (with an ASAN build)

```bash
exiv2 poc.mp4
```

### PR DESCRIPTION
**Pull request by hassec**

### CODE REVIEW

**Review by piponazo — DISMISSED** [review]
LGTM, Thanks!

File: src/quicktimevideo.cpp [hunk 1]
```diff
@@ -668,7 +668,7 @@ void QuickTimeVideo::previewTagDecoder(size_t size) {
   if (equalsQTimeTag(buf, "PICT"))
     xmpData_["Xmp.video.PreviewAtomType"] = "QuickDraw Picture";
   else
-    xmpData_["Xmp.video.PreviewAtomType"] = Exiv2::toString(buf.data());
+    xmpData_["Xmp.video.PreviewAtomType"] = std::string{buf.c_str(), 4};
```
Comment (kevinbackhouse) [inline src/quicktimevideo.cpp:671]: I checked the [documentation](https://en.cppreference.com/w/cpp/string/basic_string/basic_string) on this: it will copy 4 bytes even if some of them are null. So the `std::string::size()` will return 4 even if the string is actually shorter than that, which is a bit weird. So I wonder if it would be better to increase the size of `buf` to 5 and put a nul-terminator in `buf[4]`.

Comment (piponazo) [reply src/quicktimevideo.cpp:671]: Hi Kevin. I also looked a bit in this function, and this line looked safe to me safe to me, taking into account that in line 660 the `DataBuf` instance is of size 4, and in line 667 we do `io_->readOrThrow(buf.data(), 4);`. 

What it might prevent additional changes in the future would be to do `io_->readOrThrow(buf.data(), buf.size());` just in case the side of the `DataBuf` instance changes in the future.

Comment (kevinbackhouse) [reply src/quicktimevideo.cpp:671]: @piponazo: Yes, I think this line of code is safe. The problem that I'm talking about is only a very minor thing. This is a demo of the weird thing that can happen:

```c
#include <string>
#include <stdio.h>

int main() {
  std::string s("hi\0\0\0", 4);
  printf("%s %lu\n", s.c_str(), s.size());
  return 0;
}
```

It prints this:

```
hi 4
```

But you might expect it to print this:

```
hi 2
```

If we never call `size()` on the string then it doesn't even matter.

Comment (hassec) [reply src/quicktimevideo.cpp:671]: I figured as a first step, this is a quick fix that fixes the out-of-bounds read. 

I think what we really want is a safer utility to read strings. Maybe something like a `read_string` function on databuf similar to the `read_uintxx` functions. But that is a larger refactor that I didn't have time to implement.

**Comment by postscript-dev** [comment]
@hassec 
Before merging, can you check that the manpage's [FILE FORMAT](https://github.com/Exiv2/exiv2/blob/main/exiv2.md#file_types) section is updated with the supported formats.

**Review by kevinbackhouse — APPROVED** [review]
