### PR TITLE
Fix #742 - master

### LINKED ISSUE #742: [bug report] Program crash due to uncontrolled memory allocation on function DataBuf data(subBox.length-sizeof(box))
Hi there,

An issue was discovered in DataBuf data(subBox.length-sizeof(box)) function in image.cpp, as distributed in master and version 0.27. There is an uncontrolled memory allocation problem, leading to a program crash. I have also confirmed this issue by using addressSanitizer.

Here is the POC file. Please use the “./exiv2 -pX $POC” to reproduce the bug.
[POC.zip](https://github.com/Exiv2/exiv2/files/2961347/POC.zip)

```
subBox.length = getLong((byte*)&subBox.length, bigEndian);
subBox.type   = getLong((byte*)&subBox.type, bigEndian);

// subBox.length makes no sense if it is larger than the rest of the file
if (subBox.length > io_->size() - io_->tell()) {
     throw Error(kerCorruptedMetadata);
}
DataBuf data(subBox.length-sizeof(box));
io_->read(data.pData_,data.size_);
```

The ASAN dumps the stack trace as follows:

```
==9819==WARNING: AddressSanitizer failed to allocate 0xffffffffffffffff bytes
=================================================================
==9819==ERROR: AddressSanitizer: unknown-crash on address 0xffffffffffffffff at pc 0x0000004a9325 bp 0x7fffe470cec0 sp 0x7fffe470c670
WRITE of size 18446744073709551615 at 0xffffffffffffffff thread T0
    #0 0x4a9324 in __asan_memset (/home/wencheng/Documents/FuzzingObject/exiv2/build/bin/exiv2+0x4a9324)
    #1 0x7f3986594f9c in Exiv2::DataBuf::DataBuf(long) /home/wencheng/Documents/FuzzingObject/exiv2/src/types.cpp:141:42
    #2 0x7f39864b354c in Exiv2::Jp2Image::printStructure(std::ostream&, Exiv2::PrintStructureOption, int) /home/wencheng/Documents/FuzzingObject/exiv2/src/jp2image.cpp:506:37
    #3 0x53fa0d in (anonymous namespace)::printStructure(std::ostream&, Exiv2::PrintStructureOption, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/wencheng/Documents/FuzzingObject/exiv2/src/actions.cpp:2368:9
    #4 0x5400f2 in Action::setModeAndPrintStructure(Exiv2::PrintStructureOption, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/wencheng/Documents/FuzzingObject/exiv2/src/actions.cpp:237:16
    #5 0x5400f2 in Action::Print::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/wencheng/Documents/FuzzingObject/exiv2/src/actions.cpp:256
    #6 0x4f42f5 in main /home/wencheng/Documents/FuzzingObject/exiv2/src/exiv2.cpp:172:23
    #7 0x7f3984e1982f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #8 0x41f0a8 in _start (/home/wencheng/Documents/FuzzingObject/exiv2/build/bin/exiv2+0x41f0a8)

==9819==AddressSanitizer CHECK failed: /build/llvm-toolchain-3.8-_PD09B/llvm-toolchain-3.8-3.8/projects/compiler-rt/lib/asan/asan_report.cc:354 "((0 && "Address is not in memory and not in shadow?")) != (0)" (0x0, 0x0)
    #0 0x4c87dd in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/home/wencheng/Documents/FuzzingObject/exiv2/build/bin/exiv2+0x4c87dd)
    #1 0x4cf403 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/home/wencheng/Documents/FuzzingObject/exiv2/build/bin/exiv2+0x4cf403)
    #2 0x4c3f9b in __asan::DescribeAddress(unsigned long, unsigned long, char const*) (/home/wencheng/Documents/FuzzingObject/exiv2/build/bin/exiv2+0x4c3f9b)
    #3 0x4c4480 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) [clone .part.18] (/home/wencheng/Documents/FuzzingObject/exiv2/build/bin/exiv2+0x4c4480)
    #4 0x4a9346 in __asan_memset (/home/wencheng/Documents/FuzzingObject/exiv2/build/bin/exiv2+0x4a9346)
    #5 0x7f3986594f9c in Exiv2::DataBuf::DataBuf(long) /home/wencheng/Documents/FuzzingObject/exiv2/src/types.cpp:141:42
    #6 0x7f39864b354c in Exiv2::Jp2Image::printStructure(std::ostream&, Exiv2::PrintStructureOption, int) /home/wencheng/Documents/FuzzingObject/exiv2/src/jp2image.cpp:506:37
    #7 0x53fa0d in (anonymous namespace)::printStructure(std::ostream&, Exiv2::PrintStructureOption, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/wencheng/Documents/FuzzingObject/exiv2/src/actions.cpp:2368:9
    #8 0x5400f2 in Action::setModeAndPrintStructure(Exiv2::PrintStructureOption, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/wencheng/Documents/FuzzingObject/exiv2/src/actions.cpp:237:16
    #9 0x5400f2 in Action::Print::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/wencheng/Documents/FuzzingObject/exiv2/src/actions.cpp:256
    #10 0x4f42f5 in main /home/wencheng/Documents/FuzzingObject/exiv2/src/exiv2.cpp:172:23
    #11 0x7f3984e1982f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #12 0x41f0a8 in _start (/home/wencheng/Documents/FuzzingObject/exiv2/build/bin/exiv2+0x41f0a8)

```

### PR DESCRIPTION
**Pull request by piponazo**
This PR fixes #742 

The issue was issue to debug and the problem seems to be an incorrect/unexpected size of the subBox which is 0 with the provided POC.  

I took the opportunity to clang-format the function where the bug was happening.

### CODE REVIEW

File: src/jp2image.cpp [hunk 1]
```diff
@@ -499,8 +499,8 @@ namespace Exiv2
                             subBox.length = getLong((byte*)&subBox.length, bigEndian);
                             subBox.type   = getLong((byte*)&subBox.type, bigEndian);
 
-                            // subBox.length makes no sense if it is larger than the rest of the file
-                            if (subBox.length > io_->size() - io_->tell()) {
+                            // subBox.length makes no sense if it is larger than the rest of the file || 0
+                            if (subBox.length == 0 || subBox.length > io_->size() - io_->tell()) {
```
Comment (D4N) [inline src/jp2image.cpp]: This check is not exhaustive: imagine `subBox.length` being `sizeof(box) - 1`, then in line 506 you initialize `data` with `-1` and the whole thing blows up.

I would suggest that instead of throwing an exception here, we simply limit the size of `data` to sane values.

**Review by D4N — CHANGES_REQUESTED** [review]
Please add the reproducer from #742 to the test suite.

File: src/jp2image.cpp (hunk 1 above)
Comment (clanmills) [reply src/jp2image.cpp]:
```
                            // subBox.length makes no sense if it is larger than the rest of the file
                            if (subBox.length > io_->size() - io_->tell()) {
                                throw Error(kerCorruptedMetadata);
                            }
                            // subBox.length must be > sizeof(subBox)
                            if (subBox.length <= sizeof(subBox) ) {
                                throw Error(kerCorruptedMetadata);
                            }
```

There's an issue with `makeSlice(data,0,30)` on line 512.  https://github.com/Exiv2/exiv2/issues/744

I've just noticed there's probably an issue with '40' on makeSlide(rawData,0,40) on line 560.  This can be remedied with code similar to my suggestion for #744.

We'll need an additional test `box.length > sizeof(uuid) + sizeof(box)` about line 554 before allocating rawData.

Comment (piponazo) [reply src/jp2image.cpp]: @D4N I slightly changed the check for `subBox.length` as you suggested and added the python test.

@clanmills Let's analyse the other issue in a different branch. I do not want to mix concepts here. This PR is just about fixing #742

**Comment by clanmills** [comment]
You're right.  #742 is close and different issue.  It has its own bug report.

File: src/jp2image.cpp [hunk 2]
```diff
@@ -501,10 +501,10 @@ namespace Exiv2
                             subBox.length = getLong((byte*)&subBox.length, bigEndian);
                             subBox.type = getLong((byte*)&subBox.type, bigEndian);
 
-                            // subBox.length makes no sense if it is larger than the rest of the file || 0
-                            if (subBox.length == 0 || subBox.length > io_->size() - io_->tell()) {
+                            if (subBox.length < sizeof(box) || subBox.length > io_->size() - io_->tell()) {
```
Comment (D4N) [inline src/jp2image.cpp]: Sorry for taking so long and not taking a proper look previously, but there's another issue further down. If you check the branch starting at line 518, you'll see that we are actually reading a user controlled amount of data from `data.pData_` (or at least 3 bytes).

We definitely must fix that one too (as that's another segfault waiting to happen), however I don't want to block this PR if you feel this is out of scope.

**Review by D4N — COMMENTED** [review]
LGTM. Please tell me if you want to fix the issue that I addressed in the comment too or not. If not, I'll approve this.

File: src/jp2image.cpp (hunk 2 above)
Comment (piponazo) [reply src/jp2image.cpp]: I would suggest to create a ticket about that issue and solve it properly in other branch. When I addressed this issue I just tried to solve the bug described #742 so that we can have that fix in 0.27.1 soon.

I would like to address bigger refactorings and better testing approaches only in master, where we have more freedom to make bigger changes :innocent:

**Review by D4N — APPROVED** [review]
LGTM
