### PR TITLE
Fix long-running loop in QuickTimeVideo::sampleDesc

### LINKED ISSUE #2423: Long-running loop in QuickTimeVideo::sampleDesc
Reported by OSS-Fuzz (but hasn't been assigned an issue number).

This loop can take a very long time to complete, which could be used in a denial-of-service attack:

https://github.com/Exiv2/exiv2/blob/cf15cc52e01c9c4b890048bf11896278ea49271c/src/quicktimevideo.cpp#L1120-L1125

The problem happens when `noOfEntries` is very large and `currentStream_` does not equal either `Audio` or `Video`. (Sometimes `currentStream_` is never initialized, so its value is random.)

quicktimevideo.cpp is a new file, so this bug doesn't affect any released versions of exiv2.

poc: https://user-images.githubusercontent.com/4358136/202911830-eb64085f-b0b5-405a-8b2d-3506ede5bc4b.mp4

To reproduce:

```bash
exiv2 poc.mp4
```

(Takes a very long time to finish.)

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes: #2423 

The most important change here is to add a `break` to the loop in `QuickTimeVideo::sampleDesc`. The second important change is to make sure that all the private fields of `QuickTimeVideo` are initialized. I also did some cleanup of the types of some of the local variables.

### CODE REVIEW

File: src/quicktimevideo.cpp [hunk 1]
```diff
@@ -1094,13 +1096,12 @@ void QuickTimeVideo::timeToSampleDecoder() {
...
-  noOfEntries = buf.read_uint32(0, bigEndian);
-  size_t temp;
+  uint64_t totalframes = 0, timeOfFrames = 0;
+  const uint32_t noOfEntries = buf.read_uint32(0, bigEndian);
 
-  for (unsigned long i = 1; i <= noOfEntries; i++) {
+  for (uint32_t i = 0; i < noOfEntries; i++) {
     io_->readOrThrow(buf.data(), 4);
-    temp = buf.read_uint32(0, bigEndian);
+    const uint64_t temp = buf.read_uint32(0, bigEndian);
```
Comment (piponazo) [inline src/quicktimevideo.cpp:1104]: Does it makes sense to treat the variable `temp` as `uint64_t` when we are reading here a `uint32_t`? Since we are talking about frames in a video, I doubt we will ever need to process such a large video to need `uint64_t` for the totalFrames :)

**Review by piponazo — DISMISSED** [review]
Feel free to do something about the comment I have made or not, it is just a suggestion. Everything else looks good!

**Comment by hassec** [comment]
@kevinbackhouse looks like https://github.com/conan-io/conan-center-index/pull/14259 caused the conan problem here. 

removing: 
https://github.com/Exiv2/exiv2/blob/cf15cc52e01c9c4b890048bf11896278ea49271c/conanfile.py#L36-L37
should do the trick

File: src/quicktimevideo.cpp (hunk 1 above)
Comment (kevinbackhouse) [reply src/quicktimevideo.cpp:1104]: I did that because of the multiplication two lines later:

https://github.com/Exiv2/exiv2/blob/cf15cc52e01c9c4b890048bf11896278ea49271c/src/quicktimevideo.cpp#L1106

If `temp` is a `uint64_t` then the multiplication can't overflow. (Probably not a big deal if it does overflow, but I figure we might as well avoid it.)

Comment (piponazo) [reply src/quicktimevideo.cpp:1104]: Would it make sense to use here some of the `SafeXXX` operations then to throw in case of overflow?

**Comment by piponazo** [comment]
> @kevinbackhouse looks like [conan-io/conan-center-index#14259](https://github.com/conan-io/conan-center-index/pull/14259) caused the conan problem here.
> 
> removing:
> 
> https://github.com/Exiv2/exiv2/blob/cf15cc52e01c9c4b890048bf11896278ea49271c/conanfile.py#L36-L37
> 
> 
> should do the trick

😱 ! I'll take a look to this issue

File: src/quicktimevideo.cpp (hunk 1 above)
Comment (kevinbackhouse) [reply src/quicktimevideo.cpp:1104]: Unfortunately, we don't currently have a `Safe::multiply`. But I think it makes sense to replace this `+=` with a `Safe::add`, which will make this code safe. I'll add a follow-up commit.

**Review by piponazo — DISMISSED** [review]

**Comment by piponazo** [comment]
When you rebase this branch on top of master, the failing CI jobs should turn green (Except for the cygwin one 🙈 )

**Comment by kevinbackhouse** [comment]
Is this one ok to merge?

**Review by hassec — APPROVED** [review]
