### PR TITLE
jp2image.cpp: check size before allocation to avoid out-of-memory errors

### LINKED ISSUE #1812: 4GB allocation in jp2image.cpp
There are a couple of memory allocations in jp2image.cpp that don't check whether the amount of memory requested makes sense. This can cause a crash due to an out-of-memory error.

To reproduce:

```bash
mkdir build
cd build
cmake ..
make -j $(nproc)
ulimit -v 4194304  # don't allow more than 4GB to be allocated
./bin/exiv2 poc.jp2
```

Error message:

```
Uncaught exception: std::bad_alloc
```

poc: [poc.tar.gz](https://github.com/Exiv2/exiv2/files/6908387/poc.tar.gz)

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes: #1812

Note: I had to update some of our tests, because several of our older test files are triggering the new size check. (None of the test files that trigger the new check are valid images.)

### CODE REVIEW

File: src/jp2image.cpp [hunk 1]
```diff
@@ -538,7 +542,7 @@ static void boxes_check(size_t b,size_t m)
 
                             if (subBox.type == kJp2BoxTypeColorHeader) {
                                 long pad = 3;  // don't know why there are 3 padding bytes
-                                enforce(data.size_ >= pad, kerCorruptedMetadata);
+                                enforce(data.size_ >= pad + 4, kerCorruptedMetadata);
```
Comment (hassec) [inline src/jp2image.cpp:545]: Sorry to be annoying, but what's the origin of the ` + 4`? 
Is that to protect the `getULong()` on line 551?   
Might make it easier for future debugging to put a comment explaining that? What do you think?

Comment (kevinbackhouse) [reply src/jp2image.cpp:547]: Good point. I have added a comment.

**Review by hassec — APPROVED** [review]
