### PR TITLE
Issue 839: add bounds check.

### LINKED ISSUE #839: Out of memory error due to unchecked allocation size in LoaderTiff::getData()
This bug was found by AFL. The value of `size_` has not been checked before [this line of code](https://github.com/Exiv2/exiv2/blob/f4a37c63f2f890c16ff7192fc89a75a7c34ae82b/src/preview.cpp#L809), leading to a large allocation. This can cause `exiv2` to crash with an out-of-memory error if less than 4GB RAM is available.

issue_839_poc

Reproducible on the 0.27-maintenance branch (f4a37c6):

```
exiv2 issue_839_poc.jpg
```

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes #839.

### CODE REVIEW

File: src/preview.cpp [hunk 1]
```diff
@@ -806,6 +806,7 @@ namespace {
                 }
                 else {
                     // FIXME: the buffer is probably copied twice, it should be optimized
+                    enforce(size_ <= static_cast<uint32_t>(io.size()), kerCorruptedMetadata);
```
Comment (D4N) [inline src/preview.cpp]: Have you considered adding this `enforce` to the place where `size_` is set?

Comment (kevinbackhouse) [reply src/preview.cpp]: Yes, I tried that but the result was a bit weird. Rather than stopping with an error, `exiv2` just seemed to ignore the bad values and keep going. You can see that version of the code [here](https://github.com/kevinbackhouse/exiv2/commit/54184a3d6851f07b4d150045647ae7c6df2a7a9c). It breaks some existing tests due to the behavior that I describe.

Comment (D4N) [reply src/preview.cpp]: Well, it keeps going because that's a constructor and the only way how to abort a constructor is to throw an exception from it.

Lets keep it in the current state.

**Review by D4N — DISMISSED** [review]
Thanks for fixing this!

**Review by piponazo — DISMISSED** [review]

**Review by D4N — DISMISSED** [review]
Please squash all the commits into one.

**Review by piponazo — APPROVED** [review]
