### PR TITLE
fix: incorrectly triggered enforce check during preview extraction

### LINKED ISSUE #1829: corrupted image metadata error on preview extraction of DNG image
I have the attached dng (I zipped it in order to get it accepted by the editor), I got it from a CR3 with Adobe DNG converter x64 13.3 [IMG_7463.dng.zip](https://github.com/Exiv2/exiv2/files/6919189/IMG_7463.dng.zip)

I get:

```
$ exiv2 -ep1 /home/paolo/raw/2021-08-02/IMG_7463.dng
Exiv2 exception in extract action for file /home/paolo/raw/2021-08-02/IMG_7463.dng:
corrupted image metadata
```

my exiv2 is 0.27.2, I'm on ubuntu 20.04

Since dng has been created by Adobe, it seems weird that their converter generate a corrupted image...

Is it an exiv2 bug? or is there any other reason why exiv2 sees this dng as corrupt?

### PR DESCRIPTION
**Pull request by hassec**
This should close #1829.

The problem was an `enforce` statement inside `LoaderTiff::getData()`

I'm not an expert on the entire preview extraction stuff so take the below with a grain of salt. 
But it seems that there are previews inside a file which are defined by "stripes" or "tiles" 
If that is the case, they are inside the exifdata like below: 
```
0x0111 Exif.Image.StripOffsets                      StripOffsets                Long        1  134354
0x0117 Exif.Image.StripByteCounts                   StripByteCounts             Long        1  131328
```
Where the first one tells you at what offset into the file the preview starts and the second tells you how large the preview is in bytes.

But sometimes you get many offsets and counts, (who knows why, didn't really look into that yet, but the resulting image is in fact a preview :man_shrugging:)
```
0x0144 Exif.SubImage3.TileOffsets                   TileOffsets                 Long       12  301748 323396 354506 429600 459954 490748 523812 592136 630472 652932 678910 726818
0x0145 Exif.SubImage3.TileByteCounts                TileByteCounts              Long       12  21647 31110 75094 30354 30793 33063 68323 38336 22459 25978 47908 46601
```

And that's what would trigger the bug.
You can see that the function `LoaderTiff::getData()` behaves differently if you need to copy many chunks.
It checks each loop iteration to make sure that the value of `IdxBuf + size of current chunk` doesn't overflow the `DataBuf` we are copying the entire image into.  
It just ignored that by construction this check is going to be false on the last iteration where the two should be equal. 

I'm not sure how to make a proper test case for this without introducing a large file :/
Let's add this as yet another +1 to the long list of reasons why it would really be great to soon somehow start testing more one real files.

### CODE REVIEW

File: src/preview.cpp [hunk 1]
```diff
@@ -807,9 +807,21 @@ namespace {
...
-                        enforce(Safe::add(idxBuf, size) < size_, kerCorruptedMetadata);
-                        if (size!=0 && Safe::add(offset, size) <= static_cast<uint32_t>(io.size()))
+
+                        // the size_ parameter is originally computed by summing all values inside sizes
+                        // see the constructor of LoaderTiff
+                        // But e.g in malicious files some of thes values could be negative
+                        // That's why we check again for each step here to really make sure we don't overstep
+                        //
+                        // if we are in the last iteration we check for equality since size_ = sum(sizes)
+                        enforce(Safe::add(idxBuf, size) < size_ ||
```
Comment (kevinbackhouse) [inline src/preview.cpp:817]: Was #1829 caused by the enforce using `<` when it should have been `<=`?

```suggestion
                        enforce(Safe::add(idxBuf, size) <= size_ ||
```

**Comment by kevinbackhouse** [comment]
Should this be fixed on 0.27-maintenance?

File: src/preview.cpp (hunk 1 above)
Comment (hassec) [reply src/preview.cpp:817]: Yes, that's pretty much it. But I went for a bit stricter requirement and only allow `idxBuf+size == size_` on the last iteration of the for loop. 
That's when this case would happen on regular files.   

I'm not sure if it really makes a difference... want me to change it to just a simple `... <= size_` ?

**Comment by hassec** [comment]
I don't think so. It's a feature fix, but not a security issue.   

In fact, the problem here is that the security was a bit too strict :D

**Comment by kevinbackhouse** [comment]
But it's a bug, isn't it? On 0.27-maintenance, we could do the simpler fix of just replacing `<` with `<=`.

File: src/preview.cpp (hunk 1 above)
Comment (hassec) [reply src/preview.cpp]: Thinking about it a bit I did like the simpler version better in the end so made the change to use `<=`

Comment (hassec) [reply src/preview.cpp]: Thinking about it a bit I did like the simpler version better in the end so made the change to use `<=`

**Comment by kevinbackhouse** [comment]
I think we should fix this one on 0.27-maintenance, since it's such a simple change. Also, it looks like the bug was caused by an over-enthusiastic security fix, so it's slightly related to security!

File: src/preview.cpp (hunk 1 above)
Comment (kevinbackhouse) [reply src/preview.cpp]: I have no objection to the extra check on the final iteration. I was just thinking about the edge case where the size is 0 on the final iteration.

**Comment by hassec** [comment]
I don't have a strong opinion about this, so happy to go either way :+1:

**Review by kevinbackhouse — APPROVED** [review]

File: src/preview.cpp (hunk 1 above)
Comment (hassec) [reply src/preview.cpp]: That's what I came to wonder as well and then ended up changing it :sweat_smile:   

I'm not sure if a size 0 is an actually valid entry, so I think the current solution is the safest

**Comment by hassec** [comment]
@Mergifyio backport 0.27-maintenance
