### PR TITLE
Fix memory leak in pngimage.cpp

### LINKED ISSUE #1817: memory leak in pngimage.cpp
An array is [allocated](https://github.com/Exiv2/exiv2/blob/c6f7e4823e83229e0fe725ffe6469973570a7357/src/pngimage.cpp#L318) with `new byte[...]`, but not [deleted](https://github.com/Exiv2/exiv2/blob/c6f7e4823e83229e0fe725ffe6469973570a7357/src/pngimage.cpp#L395) if an exception is thrown because the image file is corrupt.

Reproducible on `main` and `0-27-maintenance`.

To reproduce:

```bash
mkdir build-asan
cd build-asan
cmake -DCMAKE_BUILD_TYPE=Debug -DEXIV2_TEAM_USE_SANITIZERS=ON ..
make -j $(nproc)
./bin/exiv2 -pS poc.png
```

poc: poc

output:

```
STRUCTURE OF PNG FILE: poc.png
 address | chunk |  length | data                           | checksum
       8 | eXIf  |       0 |                                | 0x00000000
Exiv2 exception in print action for file poc.png:
corrupted image metadata

=================================================================
==3123874==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7fe0aee1f717 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
    #1 0x7fe0ad10d104 in Exiv2::PngImage::printStructure(std::ostream&, Exiv2::PrintStructureOption, int) /home/kev/work/exiv2b/src/pngimage.cpp:318
    #2 0x55f7a1db76d3 in printStructure /home/kev/work/exiv2b/src/actions.cpp:2259
    #3 0x55f7a1d6bc4d in Action::Print::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/kev/work/exiv2b/src/actions.cpp:274
    #4 0x55f7a1d17974 in main /home/kev/work/exiv2b/src/exiv2.cpp:167
    #5 0x7fe0aad18564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).
```

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes: #1817

Use `DataBuf`, rather than `new[]`, so that the memory is automatically deleted if an exception is thrown.

### CODE REVIEW

**Review by hassec — DISMISSED** [review]

File: src/pngimage.cpp [hunk 1]
```diff
@@ -315,27 +315,28 @@ namespace Exiv2 {
...
 
-                    uint32_t  start  = name_l;
+                    uint32_t  start  = static_cast<uint32_t>(name_l);
                     bool      bLF    = false;
 
                     // decode the chunk
                     bool bGood = false;
                     if ( tEXt ) {
-                        bGood = tEXtToDataBuf(data+name_l,dataOffset-name_l,dataBuf);
+                        bGood = tEXtToDataBuf(data.pData_ + name_l, dataOffset-name_l, dataBuf);
```
Comment (hassec) [inline src/pngimage.cpp:333]: Looks like the windows build doesn't like the use of the `name_l` as `size_t` here.

Comment (kevinbackhouse) [reply src/pngimage.cpp]: I have added a `static_cast`.

**Review by hassec — APPROVED** [review]
