### PR TITLE
fix947_FreeBSD_BasicError_typeinfo

### LINKED ISSUE #947: Throwing an exception crashes a program on FreeBSD because typeinfo for BasicError<char> isn't exported
**Describe the bug**
GNOME Photos crashes at launch because one of its dependency, gexiv2, calls an Exiv2 function which throws an exception.

**To Reproduce**
The example program posted at https://github.com/Exiv2/exiv2/issues/644#issuecomment-452472029 is probably the most simple way to reproduce the problem. It seems to come from [`gexiv2_metadata_register_xmp_namespace` function of gexiv2](https://gitlab.gnome.org/GNOME/gexiv2/blob/gexiv2-0.12.0/gexiv2/gexiv2-metadata-xmp.cpp#L402) and it is where GNOME Photos crashes.

**Expected behavior**
No crash should happen because the exception is caught.

**Desktop:**
 - Exiv2 0.27.1
 - FreeBSD 12.0
 - Clang 6.0.1

**Additional context**
I am not sure if I understand the problem correctly, so I just post all of my findings here. This probably makes the issue description longer than it needs, but I hope the information will be helpful for you to understand the problem if you aren't going to test Exiv2 on FreeBSD.

This is what I saw when running GNOME Photos. It just crashes without printing any message.
```
$ gnome-photos
Abort trap (core dumped)
$ gdb gnome-photos gnome-photos.core
...
Core was generated by `gnome-photos'.
Program terminated with signal SIGABRT, Aborted.
(gdb) bt
#0  thr_kill () at thr_kill.S:3
#1  0x0000000801b68844 in __raise (s=6) at /usr/src/lib/libc/gen/raise.c:52
#2  0x0000000801adb079 in abort () at /usr/src/lib/libc/stdlib/abort.c:67
#3  0x00000008023d98ba in report_failure (err=<optimized out>, thrown_exception=0x80aefcc08) at /usr/src/contrib/libcxxrt/exception.cc:719
#4  0x000000080224fc01 in Exiv2::XmpProperties::nsInfoUnsafe (prefix="gnome") at /home/lantw44/gnome/source/exiv2/src/properties.cpp:2659
#5  0x000000080224fafb in Exiv2::XmpProperties::ns (prefix="gnome") at /home/lantw44/gnome/source/exiv2/src/properties.cpp:2586
#6  0x00000008004fcad2 in gexiv2_metadata_register_xmp_namespace (name=0x209d5a "http://www.gnome.org/xmp", prefix=0x20d1d6 "gnome") at ../../source/gexiv2/gexiv2/gexiv2-metadata-xmp.cpp:407
#7  0x000000000028168b in photos_application_create_window (self=0x8043381f0) at photos-application.c:813
#8  0x000000000027ff22 in photos_application_activate (application=<optimized out>) at photos-application.c:2436
#9  0x000000080172738d in _g_closure_invoke_va (closure=0x8009ff8e0, return_value=0x0, instance=0x8043381f0, args=<optimized out>, n_params=0, param_types=0x0) at ../../source/glib/gobject/gclosure.c:873
#10 0x000000080173b23b in g_signal_emit_valist (instance=0x8043381f0, signal_id=<optimized out>, detail=0, var_args=0x7fffffffd430) at ../../source/glib/gobject/gsignal.c:3306
#11 0x000000080173bba4 in g_signal_emit (instance=0x188ea, signal_id=6, detail=0) at ../../source/glib/gobject/gsignal.c:3453
#12 0x000000000027ffd8 in photos_application_command_line (application=0x8043381f0, command_line=0x8076e3340) at photos-application.c:2468
#13 0x000000080163dcfc in _g_cclosure_marshal_INT__OBJECTv (closure=0x8009ff920, return_value=0x7fffffffd550, instance=0x8043381f0, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, 
    param_types=0x80033e0e8) at ../../source/glib/gio/gmarshal-internal.c:845
#14 0x000000080172738d in _g_closure_invoke_va (closure=0x8009ff920, return_value=0x7fffffffd550, instance=0x8043381f0, args=<optimized out>, n_params=1, param_types=0x80033e0e8)
    at ../../source/glib/gobject/gclosure.c:873
#15 0x000000080173b23b in g_signal_emit_valist (instance=0x8043381f0, signal_id=<optimized out>, detail=0, var_args=0x7fffffffd740) at ../../source/glib/gobject/gsignal.c:3306
#16 0x000000080173bba4 in g_signal_emit (instance=0x188ea, signal_id=6, detail=0) at ../../source/glib/gobject/gsignal.c:3453
#17 0x000000080168fb17 in g_application_call_command_line (application=0x8043381f0, arguments=<optimized out>, options=<optimized out>, exit_status=0x7fffffffd814) at ../../source/glib/gio/gapplication.c:1076
#18 0x00000008016911cb in g_application_real_local_command_line (application=0x8043381f0, arguments=<optimized out>, exit_status=0x7fffffffd814) at ../../source/glib/gio/gapplication.c:1130
#19 0x000000080168f8b5 in g_application_run (application=0x8043381f0, argc=1, argv=0x7fffffffd8f8) at ../../source/glib/gio/gapplication.c:2523
#20 0x00000000002da87a in main (argc=1, argv=0x7fffffffd8f8) at photos-main.c:61
```

I quickly found a way to avoid the crash based on commit 04c9b181cc2c7741fcb134ccc43f2bafc1f86f19.
```diff
diff --git a/cmake/mainSetup.cmake b/cmake/mainSetup.cmake
index a4d983d4..1de6324c 100644
--- a/cmake/mainSetup.cmake
+++ b/cmake/mainSetup.cmake
@@ -13,7 +13,9 @@ set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
 
-if (NOT CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
+if (NOT ((CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang") OR
+         (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND
+          CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")))
     set(CMAKE_CXX_VISIBILITY_PRESET hidden)
     set(CMAKE_VISIBILITY_INLINES_HIDDEN 1)
 endif()
```
But this isn't a solution. It is just a workaround because it effectively disables visibility control.

In src/properties.cpp, function `XmpProperties::nsInfoUnsafe`:
```cpp
const XmpNsInfo* XmpProperties::nsInfoUnsafe(const std::string& prefix)
{
    const XmpNsInfo::Prefix pf(prefix);
    const XmpNsInfo* xn = lookupNsRegistryUnsafe(pf);
    if (!xn) xn = find(xmpNsInfo, pf);
    if (!xn) throw Error(kerNoNamespaceInfoForXmpPrefix, prefix);
    return xn;
}
```
It was the `throw` line that crashed the program. By using GDB, I found the execution of `throw` began at an internal function [`__cxa_throw` defined in /usr/src/contrib/libcxxrt/exception.cc](https://svnweb.freebsd.org/base/releng/12.0/contrib/libcxxrt/exception.cc?view=markup#l782). It then called [`throw_exception` defined in the same file](https://svnweb.freebsd.org/base/releng/12.0/contrib/libcxxrt/exception.cc?view=markup#l759) to continue the process.
```cpp
static void throw_exception(__cxa_exception *ex)
{
    // [snip]

    _Unwind_Reason_Code err = _Unwind_RaiseException(&ex->unwindHeader);
    // The _Unwind_RaiseException() function should not return, it should
    // unwind the stack past this function.  If it does return, then something
    // has gone wrong.
    report_failure(err, ex);
}
```
This was where `report_failure` in the crash dump came from. GDB told me `err` was `_URC_END_OF_STACK`, which suggested that libunwind couldn't find the function catching the exception.

There is an environment variable called `LIBUNWIND_PRINT_UNWINDING` which can be used to debug libunwind. In a working build, it successfully found the function catching the exception was `gexiv2_metadata_register_xmp_namespace`:
```
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): pc=0x802466416, start_ip=0x802466370, func=__cxa_throw, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): pc=0x8022cff61, start_ip=0x8022cfed0, func=_ZN5Exiv213XmpProperties12nsInfoUnsafeERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE, lsda=0x8020824e4, personality=0x802466a60
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): calling personality function 0x802466a60
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): _URC_CONTINUE_UNWIND
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): pc=0x8022cfe5b, start_ip=0x8022cfde0, func=_ZN5Exiv213XmpProperties2nsERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE, lsda=0x802082470, personality=0x802466a60
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): calling personality function 0x802466a60
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): _URC_CONTINUE_UNWIND
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): pc=0x8004fcad2, start_ip=0x8004fca80, func=gexiv2_metadata_register_xmp_namespace, lsda=0x8004e2d98, personality=0x802466a60
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): calling personality function 0x802466a60
libunwind: unwind_phase1(ex_ojb=0x80b08fa60): _URC_HANDLER_FOUND
```

In a broken build, it couldn't find the function. The function `gexiv2_metadata_register_xmp_namespace` existed in the call stack, but it seemed to ignore   it.
```
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x8023d9416, start_ip=0x8023d9370, func=__cxa_throw, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80224fc01, start_ip=0x80224fb70, func=_ZN5Exiv213XmpProperties12nsInfoUnsafeERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE, lsda=0x8020824e4, personality=0x8023d9a60
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): calling personality function 0x8023d9a60
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): _URC_CONTINUE_UNWIND
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80224fafb, start_ip=0x80224fa80, func=_ZN5Exiv213XmpProperties2nsERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE, lsda=0x802082470, personality=0x8023d9a60
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): calling personality function 0x8023d9a60
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): _URC_CONTINUE_UNWIND
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x8004fcad2, start_ip=0x8004fca80, func=gexiv2_metadata_register_xmp_namespace, lsda=0x8004e2d98, personality=0x8023d9a60
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): calling personality function 0x8023d9a60
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): _URC_CONTINUE_UNWIND
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x28168b, start_ip=0x281640, func=.anonymous., lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x27ff22, start_ip=0x27fef0, func=.anonymous., lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80172738d, start_ip=0x8017272c0, func=.anonymous., lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80173b23b, start_ip=0x80173aec0, func=g_signal_emit_valist, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80173bba4, start_ip=0x80173bb30, func=g_signal_emit, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x27ffd8, start_ip=0x27ff70, func=.anonymous., lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80163dcfc, start_ip=0x80163dc70, func=.anonymous., lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80172738d, start_ip=0x8017272c0, func=.anonymous., lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80173b23b, start_ip=0x80173aec0, func=g_signal_emit_valist, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80173bba4, start_ip=0x80173bb30, func=g_signal_emit, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80168fb17, start_ip=0x80168faa0, func=.anonymous., lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x8016911cb, start_ip=0x801691080, func=.anonymous., lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x80168f8b5, start_ip=0x80168f790, func=g_application_run, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x2da87a, start_ip=0x2da820, func=main, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): pc=0x27f11b, start_ip=0x27f000, func=_start, lsda=0x0, personality=0x0
libunwind: unwind_phase1(ex_ojb=0x80bb5ce60): unw_step() reached bottom => _URC_END_OF_STACK
````

Therefore, I followed the execution of `_Unwind_RaiseException` in order to find why the visibility control broke it. [`_Unwind_RaiseException` is defined in /usr/src/contrib/llvm/projects/libunwind/src/UnwindLevel1.c](https://svnweb.freebsd.org/base/releng/12.0/contrib/llvm/projects/libunwind/src/UnwindLevel1.c?view=markup#l340). It then called [`unwind_phase1` defined in the same file](https://svnweb.freebsd.org/base/releng/12.0/contrib/llvm/projects/libunwind/src/UnwindLevel1.c?view=markup#l35) to search the stack.
```cpp
    // If there is a personality routine, ask it if it will want to stop at
    // this frame.
    if (frameInfo.handler != 0) {
      __personality_routine p =
          (__personality_routine)(long)(frameInfo.handler);
      _LIBUNWIND_TRACE_UNWINDING(
          "unwind_phase1(ex_ojb=%p): calling personality function %p",
          (void *)exception_object, (void *)(uintptr_t)p);
      _Unwind_Reason_Code personalityResult =
          (*p)(1, _UA_SEARCH_PHASE, exception_object->exception_class,
               exception_object, (struct _Unwind_Context *)(cursor));
      switch (personalityResult) {
      case _URC_HANDLER_FOUND:
        // [snip] 

      case _URC_CONTINUE_UNWIND:
        // [snip]
    }
```
The key is the value of `personalityResult` here. In a working build, `_URC_HANDLER_FOUND` stopped the search. In a broken build, it was always `_URC_CONTINUE_UNWIND` until it reached the end of the stack. `personalityResult` was the return value of function pointer `p`, and `p` was [`__gxx_personality_v0` defined in /usr/src/contrib/libcxxrt/exception.cc](https://svnweb.freebsd.org/base/releng/12.0/contrib/libcxxrt/exception.cc?view=markup#l1071).

It turned out `_URC_HANDLER_FOUND` was returned from here in a working build:
```cpp
        handler_type found_handler = check_action_record(context, &lsda,
                action.action_record, realEx, &selector, ex->adjustedPtr);
        // If there's no action record, we've only found a cleanup, so keep
        // searching for something real
        if (found_handler == handler_catch)
        {
            // Cache the results for the phase 2 unwind, if we found a handler
            // and this is not a foreign exception.
            if (ex)
            {
                saveLandingPad(context, exceptionObject, ex, selector, action.landing_pad);
                ex->languageSpecificData = reinterpret_cast<const char*>(lsda_addr);
                ex->actionRecord = reinterpret_cast<const char*>(action.action_record);
                // ex->adjustedPtr is set when finding the action record.
            }
            return _URC_HANDLER_FOUND;
        }
```
[`check_action_record` is defined in the same file](https://svnweb.freebsd.org/base/releng/12.0/contrib/libcxxrt/exception.cc?view=markup#l971):
```cpp
        // We only check handler types for C++ exceptions - foreign exceptions
        // are only allowed for cleanups and catchalls.
        if (filter > 0)
        {
            std::type_info *handler_type = get_type_info_entry(context, lsda, filter);
            if (check_type_signature(ex, handler_type, adjustedPtr))
            {
                *selector = filter;
                return handler_catch;
            }
        }
```
`handler_type` was `typeinfo for Exiv2::BasicError<char>` in both working and broken build. The difference was the return value of [`check_type_signature`](https://svnweb.freebsd.org/base/releng/12.0/contrib/libcxxrt/exception.cc?view=markup#l923). In a working build, it returned `true`. In a broken build, it returned `false`.
```cpp
static bool check_type_signature(__cxa_exception *ex,
                                 const std::type_info *type,
                                 void *&adjustedPtr)
{
    // [snip]

    // If the types are the same, no casting is needed.
    if (*type == *ex_type)
    {
        adjustedPtr = exception_ptr;
        return true; // <- It should return from here.
    }


    if (type->__do_catch(ex_type, &exception_ptr, 1))
    {
        adjustedPtr = exception_ptr;
        return true;
    }

    return false; // <- But a broken build returned from here.
}
```
The result suggested it was the visibility problem of `typeinfo for Exiv2::BasicError<char>` that caused the crash. In a broken build, `typeinfo for Exiv2::BasicError<char>` couldn't be found in the output of `nm -DC`. In a working build, it was there and it was marked as `V`, a weak object.

Finally, I got a working build with this patch:
```diff
diff --git a/include/exiv2/error.hpp b/include/exiv2/error.hpp
index 42a0959c..bd74c449 100644
--- a/include/exiv2/error.hpp
+++ b/include/exiv2/error.hpp
@@ -260,7 +260,7 @@ namespace Exiv2 {
              provided to print errors to a stream.
      */
     template<typename charT>
-    class BasicError : public AnyError {
+    class EXIV2API BasicError : public AnyError {
     public:
         //! @name Creators
         //@{
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 34087004..df041890 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -145,7 +145,7 @@ endif()
 
 set_target_properties( exiv2lib_int PROPERTIES
     POSITION_INDEPENDENT_CODE ON
-    COMPILE_DEFINITIONS exiv2lib_STATIC
+#   COMPILE_DEFINITIONS exiv2lib_STATIC
 )
 
 

```
Both changes are required for `typeinfo for Exiv2::BasicError<char>` to be exported. If I only modified `include/exiv2/error.hpp`, files belonging to `exiv2lib_int` will hide it because `EXIV2API` expands to nothing when `exiv2lib_STATIC` is defined.

It can be found by using `readelf -aW` on `.o` files and searching for `_ZTIN5Exiv210BasicErrorIcEE`, the mangled name of `typeinfo for Exiv2::BasicError<char>`. In src/CMakeFiles/exiv2.dir and src/CMakeFiles/exiv2lib.dir, they are 'WEAK DEFAULT', which is fine. However, in src/CMakeFiles/exiv2lib_int.dir, they are 'WEAK HIDDEN'. The result is that the symbol became 'LOCAL HIDDEN' in the linked shared library, preventing it from being used from other libraries or programs. If `exiv2lib_STATIC` is removed, all objects have 'WEAK DEFAULT', so the linked shared library also has 'WEAK DEFAULT'.

Here is the difference of dynamic symbols between the current upstream version and the version using the above patch.
```diff
--- broken	2019-07-06 01:43:00.523185000 +0800
+++ working	2019-07-06 12:20:05.783945000 +0800
@@ -1542,6 +1542,7 @@
 V construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ofstream<char, std::__1::char_traits<char> >
 V construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >
 V construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >
+V typeinfo for Exiv2::BasicError<char>
 V typeinfo for Exiv2::HttpIo
 V typeinfo for Exiv2::IoCloser
 V typeinfo for std::__1::basic_filebuf<char, std::__1::char_traits<char> >
@@ -1550,6 +1551,7 @@
 V typeinfo for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >
 V typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >
 V typeinfo for std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >
+V typeinfo name for Exiv2::BasicError<char>
 V typeinfo name for Exiv2::HttpIo
 V typeinfo name for Exiv2::IoCloser
 V typeinfo name for std::__1::basic_filebuf<char, std::__1::char_traits<char> >
@@ -1558,6 +1560,7 @@
 V typeinfo name for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >
 V typeinfo name for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >
 V typeinfo name for std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >
+V vtable for Exiv2::BasicError<char>
 V vtable for Exiv2::HttpIo
 V vtable for Exiv2::IoCloser
 V vtable for std::__1::basic_filebuf<char, std::__1::char_traits<char> >
@@ -1572,5 +1575,44 @@
 V VTT for std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >
 w __cxa_finalize
 w _Jv_RegisterClasses
+W Exiv2::BasicError<char>::~BasicError()
+W Exiv2::BasicError<char>::~BasicError()
+W Exiv2::BasicError<char>::BasicError(Exiv2::ErrorCode)
+W Exiv2::BasicError<char>::BasicError<char [10]>(Exiv2::ErrorCode, char const (&) [10])
+W Exiv2::BasicError<char>::BasicError<char [109]>(Exiv2::ErrorCode, char const (&) [109])
+W Exiv2::BasicError<char>::BasicError<char [11]>(Exiv2::ErrorCode, char const (&) [11])
+W Exiv2::BasicError<char>::BasicError<char [13]>(Exiv2::ErrorCode, char const (&) [13])
+W Exiv2::BasicError<char>::BasicError<char [14], char [10]>(Exiv2::ErrorCode, char const (&) [14], char const (&) [10])
+W Exiv2::BasicError<char>::BasicError<char [14], char [4]>(Exiv2::ErrorCode, char const (&) [14], char const (&) [4])
+W Exiv2::BasicError<char>::BasicError<char [14], char [5]>(Exiv2::ErrorCode, char const (&) [14], char const (&) [5])
+W Exiv2::BasicError<char>::BasicError<char [15]>(Exiv2::ErrorCode, char const (&) [15])
+W Exiv2::BasicError<char>::BasicError<char [21]>(Exiv2::ErrorCode, char const (&) [21])
+W Exiv2::BasicError<char>::BasicError<char [24]>(Exiv2::ErrorCode, char const (&) [24])
+W Exiv2::BasicError<char>::BasicError<char [26]>(Exiv2::ErrorCode, char const (&) [26])
+W Exiv2::BasicError<char>::BasicError<char [37]>(Exiv2::ErrorCode, char const (&) [37])
+W Exiv2::BasicError<char>::BasicError<char [4]>(Exiv2::ErrorCode, char const (&) [4])
+W Exiv2::BasicError<char>::BasicError<char [5]>(Exiv2::ErrorCode, char const (&) [5])
+W Exiv2::BasicError<char>::BasicError<char [53]>(Exiv2::ErrorCode, char const (&) [53])
+W Exiv2::BasicError<char>::BasicError<char [7], int>(Exiv2::ErrorCode, char const (&) [7], int const&)
+W Exiv2::BasicError<char>::BasicError<char [7], long>(Exiv2::ErrorCode, char const (&) [7], long const&)
+W Exiv2::BasicError<char>::BasicError<char const*>(Exiv2::ErrorCode, char const* const&)
+W Exiv2::BasicError<char>::BasicError<char*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [7]>(Exiv2::ErrorCode, char* const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [7])
+W Exiv2::BasicError<char>::BasicError<char*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [8]>(Exiv2::ErrorCode, char* const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [8])
+W Exiv2::BasicError<char>::BasicError<char*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [9]>(Exiv2::ErrorCode, char* const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [9])
+W Exiv2::BasicError<char>::BasicError<int>(Exiv2::ErrorCode, int const&)
+W Exiv2::BasicError<char>::BasicError<long, char const*>(Exiv2::ErrorCode, long const&, char const* const&)
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [3], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [3], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [4], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [4], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*>(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const* const&)
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char* const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [13]>(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [13])
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [5]>(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [5])
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char [7]>(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const (&) [7])
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
+W Exiv2::BasicError<char>::BasicError<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long>(Exiv2::ErrorCode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long const&)
+W Exiv2::BasicError<char>::code() const
+W Exiv2::BasicError<char>::what() const
 W Exiv2::Xmpdatum& Exiv2::Xmpdatum::operator=<char [30]>(char const (&) [30])
 W Exiv2::Xmpdatum& Exiv2::Xmpdatum::operator=<int>(int const&)
```

Do you think it is OK to export `BasicError`? I think the use of `exiv2lib_STATIC` here may be incorrect because `exiv2lib_int` gets linked into a shared library, but it isn't a library which is intended to be linked staticlly into other programs.

### PR DESCRIPTION
**Pull request by clanmills**
Fix #947

### CODE REVIEW

File: include/exiv2/error.hpp [hunk 1]
```diff
@@ -260,7 +260,7 @@ namespace Exiv2 {
              provided to print errors to a stream.
      */
     template<typename charT>
-    class BasicError : public AnyError {
+    class EXIV2API BasicError : public AnyError {
```
Comment (D4N) [inline include/exiv2/error.hpp]: This breaks builds on Windows and probably opens quite the can of worms: declaring a template as export/visible is not really supported.

Comment (piponazo) [reply include/exiv2/error.hpp]: Right ... the last time I worked on this topic we reached the same conclusion ... but somehow we always forget about it when somebody opens an issue in github related with that part of the code. 

I guess the final fix for this will be to finish the work started in #685

Comment (clanmills) [reply include/exiv2/error.hpp]: Oh gosh, this isn't good news.  The changes in #685 are huge.  Because they will change the API, I'd prefer not to do that in 0.27-maintenance.

I don't think we're happy with the following hack:
```
#ifdef __FREEBSD___
class EXIV2API BasicError : public AnyError
else
class BasicError : public AnyError
#endif
```
And we should do something similar on the change in src/CMakeLists.txt

For sure, we're not putting this into v0.27.2.  We need to explore other possibilities.  @lantw44 can you comment on this please?

Comment (lantw44) [reply include/exiv2/error.hpp]: Does it work if we drop `EXIV2API` from `setMsg` in include/exiv2/error.hpp, and move "free functions, template and inline definitions" to src/error.cpp or mark them as `inline`?

Comment (clanmills) [reply include/exiv2/error.hpp]: Useful suggestions, thanks.  I'll wait to see if other in Team Exiv2 wish to comment and I'll investigate this evening.

I've created a fresh FreeBSD VM this morning to investigate your thoughts about not using the package manager to install GCC.

Comment (D4N) [reply include/exiv2/error.hpp]: > Does it work if we drop `EXIV2API` from `setMsg` in include/exiv2/error.hpp, and move "free functions, template and inline definitions" to src/error.cpp or mark them as `inline`?

`setMsg` must stay in the header because it is used in the constructor of `BasicError` and because of that it must be marked as `EXIV2API` as it otherwise will not be visible on Windows. Marking it inline is worth a try though, as that's probably the only option beside #685.

**Comment by clanmills** [comment]
Bad News. 

This is inspired by Dan's "inline" idea.  There are 4 constructors for BasicError, and they all call setMsg().  I've totally removed setMsg() and placed the code in-line in the declaration of the constructors, and declared a free function `errMsg()` in error.hpp and defined it in error.cpp.

jens.cpp still aborts.

```
[rmills@rmillsmm-freebsd2 ~/temp]$ cat jens.cpp
// file: jens.cpp
// https://github.com/Exiv2/exiv2/issues/644#issuecomment-452472029

/*
Linux:
$ c++ -std=c++98 -I/usr/local/include -L/usr/local/lib -lexiv2 jens.cpp -o jens
$ ./jens
Caught error No namespace info available for XMP prefix `gnome'
http://www.gnome.org/xmp/
$
*/

#include <exiv2/exiv2.hpp>
#include <iostream>

int main(int argc, char *argv[])
{
        try {
                Exiv2::XmpProperties::ns("gnome");
        } catch (Exiv2::Error &error) {
                std::cerr << "Caught error " << error.what() << "\n";
                Exiv2::XmpProperties::registerNs("http://www.gnome.org/xmp", "gnome");
        }
        std::cout << Exiv2::XmpProperties::ns("gnome") << std::endl;
}
[rmills@rmillsmm-freebsd2 ~/temp]$ c++ -std=c++98 -I/usr/local/include -L/usr/local/lib -lexiv2 jens.cpp -o jens
[rmills@rmillsmm-freebsd2 ~/temp]$ ./jens
Abort trap (core dumped)
[rmills@rmillsmm-freebsd2 ~/temp]$ c++ -I/usr/local/include -L/usr/local/lib -lexiv2 jens.cpp -o jens
[rmills@rmillsmm-freebsd2 ~/temp]$ ./jens
Abort trap (core dumped)
[rmills@rmillsmm-freebsd2 ~/temp]$ 
```

I have run out of time to work on this for v0.27.2.  I'll review my efforts this evening.  If I don't have any new ideas, I will defer this for v0.27.3.  @lantw44, you'll have to use your work-around in the CMake code for now.

**Comment by clanmills** [comment]
I've run ./jens through GDB:
```
root@rmillsmm-freebsd2:/home/rmills/temp # gdb jens
GNU gdb (GDB) 8.3 [GDB v8.3 for FreeBSD]
...
Reading symbols from jens...
(gdb) run
Starting program: /usr/home/rmills/temp/jens 

Program received signal SIGABRT, Aborted.
0x0000000800a4345a in thr_kill () from /lib/libc.so.7
(gdb) bt
#0  0x0000000800a4345a in thr_kill () from /lib/libc.so.7
#1  0x0000000800a41844 in raise () from /lib/libc.so.7
#2  0x00000008009b4079 in abort () from /lib/libc.so.7
#3  0x000000080083b8ba in ?? () from /lib/libcxxrt.so.1
#4  0x00000008004c5441 in Exiv2::XmpProperties::nsInfoUnsafe(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) () from /usr/local/lib/libexiv2.so.27
#5  0x00000008004c5296 in Exiv2::XmpProperties::ns(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) () from /usr/local/lib/libexiv2.so.27
#6  0x0000000000202421 in main ()
(gdb)
```

```
    const XmpNsInfo* XmpProperties::nsInfoUnsafe(const std::string& prefix)
    {
        const XmpNsInfo::Prefix pf(prefix);
        const XmpNsInfo* xn = lookupNsRegistryUnsafe(pf);
        if (!xn) xn = find(xmpNsInfo, pf);
        if (!xn) std::cout << "\n\ntrouble in nsInfoUnsafe\n\n";
        if (!xn) throw Error(kerNoNamespaceInfoForXmpPrefix, prefix);
        return xn;
    }
```

It's not throwing the error.  The `Error(int,std::string)` constructor is causing libc to terminate the program.

```
[rmills@rmillsmm-freebsd2 ~/temp]$ c++ -I/usr/local/include -L/usr/local/lib -lexiv2 jens.cpp -o jens
[rmills@rmillsmm-freebsd2 ~/temp]$ ./jens 


trouble in nsInfoUnsafe

Abort trap (core dumped)
[rmills@rmillsmm-freebsd2 ~/temp]$
```

**Comment by lantw44** [comment]
Does this patch work for you?
```diff
diff --git a/include/exiv2/error.hpp b/include/exiv2/error.hpp
index 42a0959c..1787f10c 100644
--- a/include/exiv2/error.hpp
+++ b/include/exiv2/error.hpp
@@ -260,43 +260,43 @@ namespace Exiv2 {
              provided to print errors to a stream.
      */
     template<typename charT>
-    class BasicError : public AnyError {
+    class EXIV2API BasicError : public AnyError {
     public:
         //! @name Creators
         //@{
         //! Constructor taking only an error code
-        explicit BasicError(ErrorCode code);
+        explicit inline BasicError(ErrorCode code);
 
         //! Constructor taking an error code and one argument
         template<typename A>
-        BasicError(ErrorCode code, const A& arg1);
+        inline BasicError(ErrorCode code, const A& arg1);
 
         //! Constructor taking an error code and two arguments
         template<typename A, typename B>
-        BasicError(ErrorCode code, const A& arg1, const B& arg2);
+        inline BasicError(ErrorCode code, const A& arg1, const B& arg2);
 
         //! Constructor taking an error code and three arguments
         template<typename A, typename B, typename C>
-        BasicError(ErrorCode code, const A& arg1, const B& arg2, const C& arg3);
+        inline BasicError(ErrorCode code, const A& arg1, const B& arg2, const C& arg3);
 
         //! Virtual destructor. (Needed because of throw())
-        virtual ~BasicError() throw();
+        virtual inline ~BasicError() throw();
         //@}
 
         //! @name Accessors
         //@{
-        virtual int code() const throw();
+        virtual inline int code() const throw();
         /*!
           @brief Return the error message as a C-string. The pointer returned by what()
                  is valid only as long as the BasicError object exists.
          */
-        virtual const char* what() const throw();
+        virtual inline const char* what() const throw();
 #ifdef EXV_UNICODE_PATH
         /*!
           @brief Return the error message as a wchar_t-string. The pointer returned by
                  wwhat() is valid only as long as the BasicError object exists.
          */
-        virtual const wchar_t* wwhat() const throw();
+        virtual inline const wchar_t* wwhat() const throw();
 #endif
         //@}
 
@@ -304,7 +304,7 @@ namespace Exiv2 {
         //! @name Manipulators
         //@{
         //! Assemble the error message from the arguments
-        EXIV2API void setMsg();
+        void setMsg();
         //@}
 
         // DATA
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 34087004..e1c735dc 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -145,10 +145,9 @@ endif()
 
 set_target_properties( exiv2lib_int PROPERTIES
     POSITION_INDEPENDENT_CODE ON
-    COMPILE_DEFINITIONS exiv2lib_STATIC
+    COMPILE_DEFINITIONS exiv2lib_EXPORTS
 )
 
-
 target_include_directories(exiv2lib_int PRIVATE ${ZLIB_INCLUDE_DIR})
 target_include_directories(exiv2lib PRIVATE ${ZLIB_INCLUDE_DIR})
 
diff --git a/src/error.cpp b/src/error.cpp
index c8e2d9e0..a47db000 100644
--- a/src/error.cpp
+++ b/src/error.cpp
@@ -225,7 +225,7 @@ namespace Exiv2 {
     }
 
     template<>
-    void BasicError<char>::setMsg()
+    void EXIV2API BasicError<char>::setMsg()
     {
         std::string msg = _(errMsg(code_));
         std::string::size_type pos;
@@ -262,7 +262,7 @@ namespace Exiv2 {
 
 #ifdef EXV_UNICODE_PATH
     template<>
-    void BasicError<wchar_t>::setMsg()
+    void EXIV2API BasicError<wchar_t>::setMsg()
     {
         std::string s = _(errMsg(code_));
         std::wstring wmsg(s.begin(), s.end());
```

**Comment by clanmills** [comment]
Thank You for sending this.  This is building exiv2 and jens on FreeBSD, MacOS-X and Linux.  I haven't tried yet on Windows.

I'm tired and will look at this tomorrow.  For sure, this looks promising.  Thank You very much.

**Comment by clanmills** [comment]
This has failed to build several editions of Visual Studio (and passed Visual Studio 2010).  This is typical:
```
exiv2.lib(exiv2.dll) : error LNK2005: "public: __cdecl Exiv2::BasicError<char>::BasicError<char>(enum Exiv2::ErrorCode)" (??0?$BasicError@D@Exiv2@@QEAA@W4ErrorCode@1@@Z) already defined in crwimage_int.obj [C:\Users\rmills\gnu\github\exiv2\buildserver\build\unitTests\unit_tests.vcxproj]
```
I'm going to release Exiv2 v0.27.2-RC3 today without this fix.

**Comment by phako** [comment]
That failure is odd, that's exactly what `inline` is suppose to help with.

**Comment by phako** [comment]
Am I reading the CMakeList.txt wrong or are you linking exiv2 basically twice in the unit tests:

https://github.com/Exiv2/exiv2/blob/beab2898caeaecef5a276955f73248c759b0bb0c/unitTests/CMakeLists.txt#L21

and 

https://github.com/Exiv2/exiv2/blob/beab2898caeaecef5a276955f73248c759b0bb0c/unitTests/CMakeLists.txt#L29

**Comment by lantw44** [comment]
> Am I reading the CMakeList.txt wrong or are you linking exiv2 basically twice in the unit tests:

Yes, I guess the reason to do it this way is that unit tests use `Exiv2::Internal`, which isn't exported. I am preparing a patch to remove the dependency on `libexiv2.dll` for `unit_tests.exe` to prevent Visual Studio from reporting it as a duplicate symbol. This means we will compile the source code of `libexiv2.dll` twice because we have to link exiv2lib staticlly into `libexiv2.dll`.

**Comment by piponazo** [comment]
> Am I reading the CMakeList.txt wrong or are you linking exiv2 basically twice in the unit tests:

This was done with the objective of being able to test some internal functions and classes which are not exported. It could be the reason of the error message:

```
exiv2.lib(exiv2.dll) : error LNK2005: "public: __cdecl Exiv2::BasicError<char>::BasicError<char>(enum Exiv2::ErrorCode)" (??0?$BasicError@D@Exiv2@@QEAA@W4ErrorCode@1@@Z) already defined in crwimage_int.obj [C:\Users\rmills\gnu\github\exiv2\buildserver\build\unitTests\unit_tests.vcxproj]
```

**Comment by phako** [comment]
> > Am I reading the CMakeList.txt wrong or are you linking exiv2 basically twice in the unit tests:
> 
> This was done with the objective of being able to test some internal functions and classes which are not exported. It could be the reason of the error message:
> 
> ```
> exiv2.lib(exiv2.dll) : error LNK2005: "public: __cdecl Exiv2::BasicError<char>::BasicError<char>(enum Exiv2::ErrorCode)" (??0?$BasicError@D@Exiv2@@QEAA@W4ErrorCode@1@@Z) already defined in crwimage_int.obj [C:\Users\rmills\gnu\github\exiv2\buildserver\build\unitTests\unit_tests.vcxproj]
> ```

Yes, sorry, that's what I tried to say. Forgot to add that to my commen :)

**Comment by lantw44** [comment]
Updated patch:
```diff
diff --git a/include/exiv2/error.hpp b/include/exiv2/error.hpp
index 42a0959c..1787f10c 100644
--- a/include/exiv2/error.hpp
+++ b/include/exiv2/error.hpp
@@ -260,43 +260,43 @@ namespace Exiv2 {
              provided to print errors to a stream.
      */
     template<typename charT>
-    class BasicError : public AnyError {
+    class EXIV2API BasicError : public AnyError {
     public:
         //! @name Creators
         //@{
         //! Constructor taking only an error code
-        explicit BasicError(ErrorCode code);
+        explicit inline BasicError(ErrorCode code);
 
         //! Constructor taking an error code and one argument
         template<typename A>
-        BasicError(ErrorCode code, const A& arg1);
+        inline BasicError(ErrorCode code, const A& arg1);
 
         //! Constructor taking an error code and two arguments
         template<typename A, typename B>
-        BasicError(ErrorCode code, const A& arg1, const B& arg2);
+        inline BasicError(ErrorCode code, const A& arg1, const B& arg2);
 
         //! Constructor taking an error code and three arguments
         template<typename A, typename B, typename C>
-        BasicError(ErrorCode code, const A& arg1, const B& arg2, const C& arg3);
+        inline BasicError(ErrorCode code, const A& arg1, const B& arg2, const C& arg3);
 
         //! Virtual destructor. (Needed because of throw())
-        virtual ~BasicError() throw();
+        virtual inline ~BasicError() throw();
         //@}
 
         //! @name Accessors
         //@{
-        virtual int code() const throw();
+        virtual inline int code() const throw();
         /*!
           @brief Return the error message as a C-string. The pointer returned by what()
                  is valid only as long as the BasicError object exists.
          */
-        virtual const char* what() const throw();
+        virtual inline const char* what() const throw();
 #ifdef EXV_UNICODE_PATH
         /*!
           @brief Return the error message as a wchar_t-string. The pointer returned by
                  wwhat() is valid only as long as the BasicError object exists.
          */
-        virtual const wchar_t* wwhat() const throw();
+        virtual inline const wchar_t* wwhat() const throw();
 #endif
         //@}
 
@@ -304,7 +304,7 @@ namespace Exiv2 {
         //! @name Manipulators
         //@{
         //! Assemble the error message from the arguments
-        EXIV2API void setMsg();
+        void setMsg();
         //@}
 
         // DATA
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 34087004..e1c735dc 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -145,10 +145,9 @@ endif()
 
 set_target_properties( exiv2lib_int PROPERTIES
     POSITION_INDEPENDENT_CODE ON
-    COMPILE_DEFINITIONS exiv2lib_STATIC
+    COMPILE_DEFINITIONS exiv2lib_EXPORTS
 )
 
-
 target_include_directories(exiv2lib_int PRIVATE ${ZLIB_INCLUDE_DIR})
 target_include_directories(exiv2lib PRIVATE ${ZLIB_INCLUDE_DIR})
 
diff --git a/src/error.cpp b/src/error.cpp
index c8e2d9e0..a47db000 100644
--- a/src/error.cpp
+++ b/src/error.cpp
@@ -225,7 +225,7 @@ namespace Exiv2 {
     }
 
     template<>
-    void BasicError<char>::setMsg()
+    void EXIV2API BasicError<char>::setMsg()
     {
         std::string msg = _(errMsg(code_));
         std::string::size_type pos;
@@ -262,7 +262,7 @@ namespace Exiv2 {
 
 #ifdef EXV_UNICODE_PATH
     template<>
-    void BasicError<wchar_t>::setMsg()
+    void EXIV2API BasicError<wchar_t>::setMsg()
     {
         std::string s = _(errMsg(code_));
         std::wstring wmsg(s.begin(), s.end());
diff --git a/unitTests/CMakeLists.txt b/unitTests/CMakeLists.txt
index 6dbee160..215118c9 100644
--- a/unitTests/CMakeLists.txt
+++ b/unitTests/CMakeLists.txt
@@ -1,5 +1,22 @@
 find_package(GTest REQUIRED)
 
+get_target_property(exiv2lib_SOURCES exiv2lib SOURCES)
+get_target_property(exiv2lib_int_SOURCES exiv2lib_int SOURCES)
+get_target_property(exiv2lib_COMPILE_DEFINITIONS exiv2lib COMPILE_DEFINITIONS)
+get_target_property(exiv2lib_INCLUDE_DIRECTORIES exiv2lib INCLUDE_DIRECTORIES)
+get_target_property(exiv2lib_LINK_LIBRARIES exiv2lib LINK_LIBRARIES)
+
+set(unit_tests_exiv2lib_SOURCES)
+foreach(source IN LISTS exiv2lib_SOURCES exiv2lib_int_SOURCES)
+    if(source MATCHES "\.(c|cpp|h|hpp)$")
+        if(source MATCHES ".*/.*")
+            list(APPEND unit_tests_exiv2lib_SOURCES "${source}")
+        else()
+            list(APPEND unit_tests_exiv2lib_SOURCES "../src/${source}")
+        endif()
+    endif()
+endforeach()
+
 add_executable(unit_tests mainTestRunner.cpp
     gtestwrapper.h
     test_types.cpp
@@ -14,13 +31,24 @@ add_executable(unit_tests mainTestRunner.cpp
     test_helper_functions.cpp
     test_slice.cpp
     test_image_int.cpp
-    $<TARGET_OBJECTS:exiv2lib_int>
+    ${unit_tests_exiv2lib_SOURCES}
+)
+
+target_compile_definitions(unit_tests
+    PRIVATE
+        exiv2lib_STATIC
+        ${exiv2lib_COMPILE_DEFINITIONS}
+)
+
+target_include_directories(unit_tests
+    PRIVATE
+        ${exiv2lib_INCLUDE_DIRECTORIES}
 )
 
 #TODO Use GTest::GTest once we upgrade the minimum CMake version required
 target_link_libraries(unit_tests
     PRIVATE
-        exiv2lib
+        ${exiv2lib_LINK_LIBRARIES}
         ${GTEST_BOTH_LIBRARIES}
 )
 
@@ -50,4 +78,4 @@ endif()
 
 if (MSVC)
     set_target_properties(unit_tests PROPERTIES LINK_FLAGS "/ignore:4099")
-endif()
\ No newline at end of file
+endif()
```

**Comment by clanmills** [comment]
Jenkins/Visual Studio 2017 is happy and unit tests have been run (MacOS-X, Linux, Cygwin, MinGW and MSVC).

When the CI lights turn GREEN, could somebody please **Approve** the change and it will go into Exiv2 v0.27.2-RC3 and I'll publish that later today.  I don't plan any code changes to 0.27.2 before release on 2019-07-31 (Two weeks today).

Great Work Everybody.  I'm going back to cutting the hedge and other garden chores!

File: unitTests/CMakeLists.txt [hunk 2]
```diff
@@ -14,13 +31,24 @@ add_executable(unit_tests mainTestRunner.cpp
     test_helper_functions.cpp
     test_slice.cpp
     test_image_int.cpp
-    $<TARGET_OBJECTS:exiv2lib_int>
+    ${unit_tests_exiv2lib_SOURCES}
```
Comment (piponazo) [inline unitTests/CMakeLists.txt]: I would not change this. The idea of using the OBJECT library is to not recompile things. With a CMake OBJECT library we just take the .o files compiled while generating `exiv2lib` and we reuse them in the test target. With this change, we would be compiling all these files twice.

Comment (lantw44) [reply unitTests/CMakeLists.txt]: The reason of doing so is that Windows seems to distinguish between normal symbols and DLL-imported symbols. If I just take the object files of `exiv2lib_int` and `exiv2lib` and put them here, Visual Studio complains that symbols it expects to be provided by a DLL ends up being linked statically. Therefore, I use `exiv2lib_STATIC` macro to disable `dllimport` and `dllexport` attributes and compile the same source files again in order to generate object files which can be linked statically.

**Comment by clanmills** [comment]
Folks:  This is failing the build on the Mac on the CI machine, but passes on my laptop when I build with:
```
CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DEXIV2_ENABLE_VIDEO=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_ENABLE_NLS=OFF -DEXIV2_ENABLE_CURL=ON"
```

Here's the transcript from the CI build machine:  https://travis-ci.org/Exiv2/exiv2/jobs/560032789

```
Scanning dependencies of target unit_tests
[ 12%] Building CXX object unitTests/CMakeFiles/unit_tests.dir/mainTestRunner.cpp.o
In file included from <built-in>:374:
<command line>:2:37: error: whitespace recommended after macro name [-Werror]
#define exiv2lib_COMPILE_DEFINITIONS-NOTFOUND 1
```

This somehow related to the new code:
```
+get_target_property(exiv2lib_COMPILE_DEFINITIONS exiv2lib COMPILE_DEFINITIONS)
...
+target_compile_definitions(unit_tests
+    PRIVATE
+        exiv2lib_STATIC
+        ${exiv2lib_COMPILE_DEFINITIONS}
+)
```

What's "-NOTFOUND"?  I think the negative "-" is causing the problem!  So close!

File: unitTests/CMakeLists.txt (hunk 2 above)
Comment (piponazo) [reply unitTests/CMakeLists.txt]: oh I see. Thanks for the feedback and the efforts for dealing with this issue :+1:

**Comment by piponazo** [comment]
> What's "-NOTFOUND"? I think the negative "-" is causing the problem! So close!

For some reason, it seems that we do not have compile definitions for that target on Mac OSX. We should be able to identify that in the CMake code and only add them if they are available. I will push a commit in this branch with the needed change.

**Review by piponazo — APPROVED** [review]

**Comment by clanmills** [comment]
Oh boy, are we having fun.  Luis has gone to bed (and why not).  GitLab is failing on CentOS saying:
```
File /var/cache/yum/x86_64/7/epel/metalink.xml does not exist
Could not parse metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64 error was 
No repomd file
Uploading artifacts...
WARNING: build/: no matching files                 
ERROR: No files to upload                          
ERROR: Job failed: exit code 1
```
Eh? @D4N  Any ideas?
https://gitlab.com/D4N/exiv2/-/jobs/253807133

File: unitTests/CMakeLists.txt (hunk 2 above)
Comment (clanmills) [reply unitTests/CMakeLists.txt]: @lantw44  I support @piponazo in thanking you for dealing with this issue.  You (and @kevinbackhouse) are the best contributors outside of Team Exiv2 in 2019.  Thank you very much.

When I write the release notes, I like to acknowledge contributors by name.  Here's the 

*Exiv2 v0.27.2.2 = Exiv2 v0.27.2 RC2*

_Second Release Candidate for quarterly “dot” release of Exiv2 v0.27.2_

A huge thank you to Kevin for outstanding contributions to this release.
Thank You to Dan and Luis for their solid efforts on Exiv2.
Thank You to Andreas S for representing Team Exiv2 at LGM 2019.
Contributors: Jens, Nehal, Phil, Toni

I'd like to give **YOU** a _**"huge thank you also"**_ in v0.27.2 if you'd like to tell me your name!

@phako: You'll see I have already acknowledged you.  Thank You also for your contribution.

**Comment by lantw44** [comment]
> GitLab is failing on CentOS saying:

I think it is just a temporary networking issue. Retrying the build may fix it.

**Comment by clanmills** [comment]
@piponazo I believe we're finally done on this.  Can you merge into 0.27-maintenance and I can get 0.27.2-RC2 finished.  Phew!

@lantw44 Don't forget to tell me your name, so I can thank you in the release notes.  My email is robin@clanmills.com
