### PR TITLE
Fix integer overflow in print0x0007

### LINKED ISSUE #1912: UBSAN error in print0x0007
I noticed this failure in [quick fuzz](https://github.com/Exiv2/exiv2/runs/3625961013?check_suite_focus=true#step:5:1152) run on a pull request. This discovery is due to the increased fuzzing coverage of the print functions added in #1806.

To reproduce, you need a sanitizer build:

```bash
mkdir build-asan
build-asan/
cmake -DCMAKE_BUILD_TYPE=Debug -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DEXIV2_TEAM_USE_SANITIZERS=ON ..
make
./bin/exiv2 -Pt poc.jpg
```

poc: poc

Error message:

```
/home/kev/work/exiv2_mergify/src/tags_int.cpp:2778:57: runtime error: signed integer overflow: 32511318 * 3600 cannot be represented in type 'int'
```

I do not consider this a security bug, because the integer overflow doesn't cause anything bad to happen in a normal build. It just prints a weird date.

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes #1912.

Do the calculation in `double` to avoid integer overflow when the number of seconds is greater than `INT_MAX`.

### CODE REVIEW

File: src/tags_int.cpp [hunk 1]
```diff
@@ -2767,15 +2767,17 @@ namespace Exiv2 {
...
-
-            const int hh = static_cast<int>(sec / 3600);
-            const int mm = static_cast<int>((sec - 3600 * hh) / 60);
-            const float ss = sec - 3600 * hh - 60 * mm;
+            const double fraction = fmod(t,1);
+            if (fraction != 0) p = 1;
+            const double seconds = t - fraction;
+            const double ss = fmod(seconds, 60);
+            const double minutes = (seconds - ss)/60;
+            const double mm = fmod(minutes, 60);
```
Comment (kmilos) [inline src/tags_int.cpp:2779]: I realize these will be printed as integers below, but maybe the code reflects the intent better if the cast to int for mm and hh is kept here?

Comment (kevinbackhouse) [reply src/tags_int.cpp]: I updated it. I added an extra `enforce`, because the cast to `int` could crash if `t == NaN`. I also added an `fmod(hours,24)` which wasn't there in the old code, because otherwise casting the hours to `int` could overflow.

**Review by kmilos — APPROVED** [review]
LGTM
