### PR TITLE
Check bounds of jpg_img_off and jpg_img_len

### LINKED ISSUE #857: Out of memory error due to unchecked allocation size in RafImage::readMetadata()
There is no bounds check on the size of `jpg_img_len` at [rafimage.cpp:300](https://github.com/Exiv2/exiv2/blob/c0ecc2ae36f34462be98623deb85ba1747ae2175/src/rafimage.cpp#L300), leading to an out-of-memory exception.

issue_857_poc

Reproducible on the 0.27-maintenance branch ([c0ecc2a](https://github.com/Exiv2/exiv2/commit/c0ecc2ae36f34462be98623deb85ba1747ae2175)):

```
exiv2 issue_857_poc.jpg
```

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes #857.

### CODE REVIEW

File: src/rafimage.cpp [hunk 1]
```diff
@@ -289,17 +291,31 @@ namespace Exiv2 {
...
+        if (io_->read(jpg_img_length, 4) != 4) throw Error(kerFailedToReadImageData);
+        uint32_t jpg_img_off_u32 = Exiv2::getULong((const byte *) jpg_img_offset, bigEndian);
+        uint32_t jpg_img_len_u32 = Exiv2::getULong((const byte *) jpg_img_length, bigEndian);
+
+        enforce(Safe::add(jpg_img_off_u32, jpg_img_len_u32) <= io_->size(), kerCorruptedMetadata);
+
+#if LONG_MAX < UINT_MAX
+        enforce(jpg_img_off_u32 <= static_cast<uint32_t>(std::numeric_limits<long>::max()),
+                kerCorruptedMetadata);
+        enforce(jpg_img_off_u32 <= static_cast<uint32_>(std::numeric_limits<long>::max()),
```
Comment (D4N) [inline src/rafimage.cpp]: This is a copy of line 305 the `t` missing after `uint32_`

**Review by D4N — COMMENTED** [review]
Overall this looks good to me, only please correct the oddity inside the `#ifdef` block.

File: src/rafimage.cpp (hunk 1 above)
Comment (kevinbackhouse) [reply src/rafimage.cpp]: Good catch, thanks. It's fixed now.

File: src/rafimage.cpp [hunk 2]
```diff
@@ -289,17 +291,31 @@ namespace Exiv2 {
...
+        if (io_->read(jpg_img_offset, 4) != 4) throw Error(kerFailedToReadImageData);
         byte jpg_img_length [4];
-        io_->read(jpg_img_length, 4);
-        long jpg_img_off = Exiv2::getULong((const byte *) jpg_img_offset, bigEndian);
-        long jpg_img_len = Exiv2::getULong((const byte *) jpg_img_length, bigEndian);
+        if (io_->read(jpg_img_length, 4) != 4) throw Error(kerFailedToReadImageData);
+        uint32_t jpg_img_off_u32 = Exiv2::getULong((const byte *) jpg_img_offset, bigEndian);
+        uint32_t jpg_img_len_u32 = Exiv2::getULong((const byte *) jpg_img_length, bigEndian);
+
+        enforce(Safe::add(jpg_img_off_u32, jpg_img_len_u32) <= io_->size(), kerCorruptedMetadata);
```
Comment (D4N) [inline src/rafimage.cpp]: Out of interest: where did you take this check from? It makes sense to me, checking that offset+length are not out of bounds of the image, but I am not really familiar with the intricacies of this image format.

Comment (kevinbackhouse) [reply src/rafimage.cpp]: I deduced it from the code below. It seeks `jpg_img_off + 12` from the beginning of the file, then reads `jpg_img_len - 12` bytes. I am also pretty sure there was a bug in the `io_->read` on line 302, because it used to read `buf.size_ - 12` bytes, but then passes `buf.size_` bytes to `TiffParser::decode`. So I changed that line of code to read `buf.size_` bytes, which I am pretty sure is what is what it ought to do.

**Review by D4N — DISMISSED** [review]
LGTM! Please squash and merge this (whoever presses the merge button this).

**Comment by D4N** [comment]
@kevinbackhouse Rebase & squash again please.

**Review by piponazo — DISMISSED** [review]

**Review by piponazo — APPROVED** [review]
