### PR TITLE
makernotes: workaround for Olympus header corruption

### LINKED ISSUE #2542: olympus makernotes get lost or corrupt with 0.27.6
#### **Describe the bug**
olympus makernotes get lost or corrupt with 0.27.6

#### **To Reproduce**
```
$ exiv2 --version
exiv2 0.27.6
```

```
$ exiv2 -pa 42_IndexError.jpg | grep -c Olympus
132
```
→ 132 lines of Olympus Makernotes

```
$ exiv2 -M"add  Exif.Photo.UserComment MyComment4" 42_IndexError.jpg
```

```
$ exiv2 -pa 42_IndexError.jpg | grep Olympus -c
Error: Failed to read Olympus IFD Makernote header.
0
```
→ 0 line of Olympus Makernotes + error

Input file can be taken here: https://github.com/ianare/exif-samples/raw/master/jpg/tests/42_IndexError.jpg

#### **Expected behavior**
Makernotes should still be there after adding a tag.

#### **Desktop (please complete the following information):**
- Debian testing
- Exiv2 version and source: 0.27.6 from debian testing

### PR DESCRIPTION
**Pull request by kmilos**
Addresses https://github.com/Exiv2/exiv2/issues/2542 as a workaround rather than a proper solution.

Should be able to parse the data back, but still leaves a "corrupted" file that other apps might have trouble with...

@tenzap I think this should also apply to 0.27 branch (w/ maybe some minimal tweaks), so please feel free to test.

### CODE REVIEW

File: src/makernote_int.cpp [hunk 1]
```diff
@@ -654,6 +654,13 @@ TiffComponent* newIfdMn2(uint16_t tag, IfdId group, IfdId mnGroup) {
 
 TiffComponent* newOlympusMn(uint16_t tag, IfdId group, IfdId /*mnGroup*/, const byte* pData, size_t size,
                             ByteOrder /*byteOrder*/) {
+  // FIXME: workaround for overwritten OM System header in Olympus files (https://github.com/Exiv2/exiv2/issues/2542)
+  if (size >= 14 && std::string(reinterpret_cast<const char*>(pData), 14) == std::string("OM SYSTEM\0\0\0II", 14)) {
```
Comment (neheb) [inline src/makernote_int.cpp:658]: No need for the second std::string constructor.

Comment (neheb) [reply src/makernote_int.cpp:658]: I guess bump the number to 15.

Comment (kmilos) [reply src/makernote_int.cpp:658]: It's not guaranteed the char at 15 is a null...

**Review by neheb — APPROVED** [review]

**Comment by kmilos** [comment]
Is there an appetite to backport for a 0.27.7 hotfix (w/ maybe a few more select cherry-picks)? @nehaljwani @kevinbackhouse @piponazo @postscript-dev @hassec

**Comment by kevinbackhouse** [comment]
> Is there an appetite to backport for a 0.27.7 hotfix (w/ maybe a few more select cherry-picks)? @nehaljwani @kevinbackhouse @piponazo @postscript-dev @hassec

Yes, that makes sense. My understanding from quickly reading #2542 is that this was a regression from 0.27.5 to 0.27.6.

**Comment by kmilos** [comment]
Not a regression per se, as the feature responsible for the bug wasn't there in 0.27.5 at all.

**Comment by nehaljwani** [comment]
Feel free to open a pull request for the 0.27-maintenance branch and I'll cut a release after it is merged.

**Comment by kmilos** [comment]
Great, can you please create a 0.27.7 milestone then as well?

Any other changes we might want to backport? @kevinbackhouse @piponazo @postscript-dev @hassec

**Comment by nehaljwani** [comment]
@kmilos Is now a good time to cut a release with the backports?

**Comment by nehaljwani** [comment]
**Exiv2 v0.27.7 2023-05-13**

| Topic          | More Info |
|:--             |:--        | 
| Remaining ( 0) | https://github.com/Exiv2/exiv2/milestone/11 |
| Completed (3) | https://github.com/Exiv2/exiv2/milestone/11?closed=1 |

**Exiv2 v0.27.7 Acknowledgements**

According to `git shortlog -s -n v0.27.6..v0.27.7`
| Commits          | Author |
|:--             |:--        | 
|    8 | Miloš Komarčević
|    2 | Peter Kovář
|    1 | Nehal J Wani

**Exiv2 v0.27.7 Release Notes**

|  Group        | PR     |  Topic                                        | Issue  |
|:---           |:--     |:--                                            |:--     |
| **Bugs & Fixes**  | #2579 | makernotes: workaround for Olympus header corruption | #2542
|               | #2578 | Corrected JPEG XL file type |
|               | #2614 | BMFF: fix handling of boxes w/ zero length or type  | https://github.com/darktable-org/darktable/issues/14473
| **CI**         | #2604  | CI: Bump conan version | 

If I've failed to acknowledge anyone's contribution, I apologize. Please let me know and I'll update this comment.
